<?xml version="1.0" encoding="UTF-8"?>
<!--
    Copyright (c) 2026 Oracle and/or its affiliates.
-->

<project xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"
        xmlns="http://maven.apache.org/POM/4.0.0"
        xsi:schemaLocation="http://maven.apache.org/POM/4.0.0 https://maven.apache.org/xsd/maven-4.0.0.xsd">
    <modelVersion>4.0.0</modelVersion>
    <parent>
        <groupId>com.oracle.helidon.oci.metering</groupId>
        <artifactId>helidon-oci-metering-project</artifactId>
        <version>2.0.0-SNAPSHOT</version>
        <relativePath>../pom.xml</relativePath>
    </parent>

    <artifactId>helidon-oci-metering-cp</artifactId>

    <name>Helidon OCI Metering Control Plane</name>

    <dependencies>
        <dependency>
            <groupId>com.oracle.pic.bling</groupId>
            <artifactId>metering-agent</artifactId>
        </dependency>
        <dependency>
            <groupId>com.oracle.pic.kiev</groupId>
            <artifactId>kiev-core</artifactId>
        </dependency>
        <dependency>
            <groupId>com.oracle.pic.kiev</groupId>
            <artifactId>kiev-library</artifactId>
            <!--
                We need kiev-library for the MappedDataStore API used to create metering-agent MeteringLogStores.
                The application supplies however much of the full Kiev client/DB/S2S transitive tree it needs.
            -->
            <exclusions>
                <exclusion>
                    <groupId>com.oracle.pic.kiev</groupId>
                    <artifactId>service-client</artifactId>
                </exclusion>
                <exclusion>
                    <groupId>com.oracle.pic.kiev</groupId>
                    <artifactId>kiev-db-common</artifactId>
                </exclusion>
                <exclusion>
                    <groupId>com.oracle.pic.kiev</groupId>
                    <artifactId>client-registry</artifactId>
                </exclusion>
                <exclusion>
                    <groupId>com.oracle.pic.commons</groupId>
                    <artifactId>s2s-core-util</artifactId>
                </exclusion>
                <exclusion>
                    <groupId>com.oracle.pic.commons</groupId>
                    <artifactId>s2s-client-util</artifactId>
                </exclusion>
            </exclusions>
        </dependency>
        <dependency>
            <groupId>com.oracle.pic.bling</groupId>
            <artifactId>lease-kiev</artifactId>
        </dependency>
        <dependency>
            <groupId>io.helidon.config</groupId>
            <artifactId>helidon-config</artifactId>
        </dependency>
        <dependency>
            <groupId>io.helidon.config.metadata</groupId>
            <artifactId>helidon-config-metadata</artifactId>
        </dependency>
        <dependency>
            <groupId>io.helidon.service</groupId>
            <artifactId>helidon-service-registry</artifactId>
        </dependency>
        <dependency>
            <groupId>io.helidon.json</groupId>
            <artifactId>helidon-json</artifactId>
        </dependency>
        <dependency>
            <groupId>org.junit.jupiter</groupId>
            <artifactId>junit-jupiter-api</artifactId>
            <scope>test</scope>
        </dependency>
        <dependency>
            <groupId>org.hamcrest</groupId>
            <artifactId>hamcrest-all</artifactId>
            <scope>test</scope>
        </dependency>
        <dependency>
            <groupId>org.mockito</groupId>
            <artifactId>mockito-core</artifactId>
            <scope>test</scope>
        </dependency>
        <dependency>
            <groupId>io.helidon.common.testing</groupId>
            <artifactId>helidon-common-testing-junit5</artifactId>
            <scope>test</scope>
        </dependency>
    </dependencies>

    <build>
        <plugins>
            <plugin>
                <groupId>org.apache.maven.plugins</groupId>
                <artifactId>maven-compiler-plugin</artifactId>
                <configuration>
                    <annotationProcessorPaths>
                        <path>
                            <groupId>io.helidon.codegen</groupId>
                            <artifactId>helidon-codegen-apt</artifactId>
                            <version>${helidon.version}</version>
                        </path>
                        <path>
                            <groupId>io.helidon.builder</groupId>
                            <artifactId>helidon-builder-codegen</artifactId>
                            <version>${helidon.version}</version>
                        </path>
                        <path>
                            <groupId>io.helidon.service</groupId>
                            <artifactId>helidon-service-codegen</artifactId>
                            <version>${helidon.version}</version>
                        </path>
                        <path>
                            <groupId>io.helidon.codegen</groupId>
                            <artifactId>helidon-codegen-helidon-copyright</artifactId>
                            <version>${helidon.version}</version>
                        </path>
                        <path>
                            <groupId>com.oracle.helidon.oci</groupId>
                            <artifactId>helidon-oci-codegen</artifactId>
                            <version>${project.version}</version>
                        </path>
                    </annotationProcessorPaths>
                </configuration>
            </plugin>
            <plugin>
                <groupId>org.apache.maven.plugins</groupId>
                <artifactId>maven-jar-plugin</artifactId>
                <configuration>
                    <archive>
                        <manifestEntries>
                            <Automatic-Module-Name>com.oracle.helidon.oci.metering.cp</Automatic-Module-Name>
                        </manifestEntries>
                    </archive>
                </configuration>
            </plugin>
            <plugin>
                <groupId>org.apache.maven.plugins</groupId>
                <artifactId>maven-enforcer-plugin</artifactId>
            </plugin>
        </plugins>
    </build>
</project>
