#
# Copyright (c) 2026 Oracle and/or its affiliates.
#

{
  # Example-only downstream routing spec used by the Splat validation profile.
  hostHeaders: [
    "helidon-example.{IAAS-DOMAIN-NAME}",
    "helidon-example.svc"
  ]
  endpoint: "https://helidon-example.svc.ad{AD}.{REGION}"
  mtlsConfigKey: node-certs
  readTimeoutMillis: 20000
  connectTimeoutMillis: 10000
}
