#
# Copyright (c) 2026 Oracle and/or its affiliates.
#

{
  # Example-only Splat validation config.
  serviceName: helidonExample
  proxyFleets: ["default"]
  apiYamlLocation: "${project.basedir}/src/main/resources/swagger/robot-api.yaml"
  downstreamSpecLocation: "${project.basedir}/src/main/splat/downstream.conf"
  outputApiLocation: "${project.build.directory}/splat-internal-api.json"
  outputAdoptionReportLocation: "${project.build.directory}/splat-adoption-report.json"
  isVibe: false
  allowUnknownSplatFields: false
  splatAdoption: {
    failIfNotDone: false
    enabledValidations: [
      "authn",
      "authz",
      "audit",
      "async-audit",
      "distributed-throttling",
      "per-tenant-throttling",
      "per-user-throttling",
      "resource-locking",
      "tag-store",
      "fetcher-resource-load"
    ]
    exemptions: {
      "authn": ["helidonExample.*"],
      "authz": ["helidonExample.*"],
      "audit": ["helidonExample.*"],
      "async-audit": ["helidonExample.*"],
      "distributed-throttling": ["helidonExample.*"],
      "per-tenant-throttling": ["helidonExample.*"],
      "per-user-throttling": ["helidonExample.*"],
      "resource-locking": ["helidonExample.*"],
      "tag-store": ["helidonExample.*"],
      "fetcher-resource-load": ["helidonExample.*"]
    }
  }
}
