runnerTag: latest
name: oci-helidon
team: Helidon
phoneBookId: helidon
description: Helidon integration modules for internal OCI services
majorversion: 0
minorversion: 1
shortversion: ${majorversion}.${minorversion}
snapshotVersion: ${shortversion}-SNAPSHOT
version: ${shortversion}${?BLD_BRANCH_SUFFIX}.${BLD_NUMBER}
triggerOnCommitBranches: ["master", "pull-requests"]
releaseBranches: ["master"]

authCompartmentOcid: "ocid1.compartment.oc1..aaaaaaaabkst6bl3wn5qtatfzkzghw5z5grzapbgmsfcercnagfrntw3d5pq"

steps:
    [
        {
            name: compilesource
            type: maven
            runnerImage: build-runner-maven-graalvm22-jdk17
            javaVersion: jdk-17
            mavenCommands: [
                { goal: "validate", args: "--global-toolchains build_config/toolchains.xml -N -DrequireVersion="${snapshotVersion} },
                { goal: "versions:set", args: "--global-toolchains build_config/toolchains.xml -DnewVersion="${version}" -DprocessAllModules=true"},
                { goal: "install", args: "--global-toolchains build_config/toolchains.xml"}
            ]
            artifacts: [
                "**"
            ]
        },
        {
            name: publish_oci_helidon_maven_artifacts
            type: publishmaven
            dependsOn: compilesource
            repository: build-service-test-maven-local
        },
    ]