#
# Copyright (c) 2023, 2024 Oracle and/or its affiliates.
#

# For more information about configuring ocibuild.conf follow https://confluence.oci.oraclecorp.com/display/BLD/Build+Service+ocibuild.conf+Reference+Guide

runnerTag: latest

name: oci-helidon
team: Helidon
phoneBookId: helidon
description: Helidon integration modules for internal OCI services

# Development releases start with 0
# TODO: For releases change major version
majorversion: 0
minorversion: 1
shortversion: ${majorversion}.${minorversion}
snapshotVersion: ${shortversion}-SNAPSHOT
version: ${shortversion}${?BLD_BRANCH_SUFFIX}.${BLD_NUMBER}

triggerOnCommitBranches: ["main", "pull-requests", "release-*"]
releaseBranches: ["main", "release-*"]

# Creates a unique tag on the commit when a build from a release branch (see releaseBranches) completes
# TODO: For releases set enabled to true
bitbucketTag: {"enabled": false, "tagName": ${version}, "description": "Build Service Created Tag"}

initialBuildNumber: {
  "main" : 1
  "release-*" : 1
  "*" : 1
}

releaseArtifactoryRepo: helidon-oci-release-maven-local
snapshotArtifactoryRepo: helidon-oci-snapshot-maven-local

# see https://confluence.oci.oraclecorp.com/pages/viewpage.action?spaceKey=BLD&title=Build+Service+AuthZ+Onboarding
# helidon compartment from helidonocidev tenancy
authCompartmentOcid: "ocid1.compartment.oc1..aaaaaaaaiwoctrgf6w6rtq7az62fabscwgzbax2iepwu2qlub5qzcvabn5wa"

steps:
    [
        {
            name: compilesource
            type: maven
            javaVersion: jdk-21
            mavenCommands: [
                { goal: "validate", args: "--global-toolchains build_config/toolchains.xml -N -DrequireVersion="${snapshotVersion} },
                { goal: "versions:set versions:set-property", args: "--global-toolchains build_config/toolchains.xml -DnewVersion="${version}" -DprocessAllModules=true -Dproperty=helidon.oci.version"},
                { goal: "install", args: "--global-toolchains build_config/toolchains.xml"}
            ]
            artifacts: [
                "**"
            ]
        },
        {
            name: publish_oci_helidon_maven_artifacts
            type: publishmaven
            dependsOn: compilesource
            repository: ${releaseArtifactoryRepo}
            snapshotRepository: ${snapshotArtifactoryRepo}
            multiModuleDeploy: true
        }
    ]
