#
# Copyright (c) 2023, 2025 Oracle and/or its affiliates.
#

# For more information about configuring ocibuild.conf follow https://confluence.oci.oraclecorp.com/display/BLD/Build+Service+ocibuild.conf+Reference+Guide

runnerTag: latest

name: oci-helidon
team: Helidon
phoneBookId: helidon
description: Helidon integration modules for internal OCI services

# Our approach to releases:
#  Merges to main produce SNAPSHOT builds
#  Merges to release-* produce release builds
#  We manage version numbers explicitly and do not rely on magically populated build service variables.

# Branches that publish artifacts.
# main publishes SNAPSHOT artifacts and does not create a source tag
# release-*  publishes release artifacts and creates a source tag
releaseBranches: ["main", "release-*"]
snapshotBranches: ["main"]
triggerOnCommitBranches: ["main", "pull-requests", "release-*"]

# By default we are producing SNAPSHOT builds
# TODO: For releases set to released version
version: 1.1.0-SNAPSHOT
# version: 1.1.0

# By default we don't create a tag, but do it for releases
# TODO: For releases set enabled to true
bitbucketTag: {"enabled": false, "tagName": ${version}, "description": "Release Tag"}

releaseArtifactoryRepo: helidon-oci-release-maven-local
snapshotArtifactoryRepo: helidon-oci-snapshot-maven-local

# see https://confluence.oci.oraclecorp.com/pages/viewpage.action?spaceKey=BLD&title=Build+Service+AuthZ+Onboarding
# helidon compartment from helidonocidev tenancy
authCompartmentOcid: "ocid1.compartment.oc1..aaaaaaaaiwoctrgf6w6rtq7az62fabscwgzbax2iepwu2qlub5qzcvabn5wa"

# This will make .git directory available in all steps in their builds.
# Its need by our helidon enforcer plugin esp. for copyright
enableGit: true

# Cache maven artifacts for re-use across builds (and, apparently, across steps).
# https://confluence.oci.oraclecorp.com/display/BLD/User+Guide+for+caching+3PLs+during+Builds
useCache: true

steps:
    [
        {
            name: compileplugins
            type: maven
            javaVersion: jdk-21
            mavenCommands: [
              { goal: "install", args: "-B --global-toolchains build_config/toolchains.xml -f repackaged-oci/repackage-plugin/pom.xml install -DskipTests"},
              { goal: "install", args: "-B --global-toolchains build_config/toolchains.xml -f swagger-maven-plugin/pom.xml install -DskipTests"}
            ]
            artifacts: [
            "**"
            ]
        },
        {
            name: compilesource
            type: maven
            dependsOn: compileplugins
            javaVersion: jdk-21
            mavenCommands: [
                { goal: "install", args: "-B --global-toolchains build_config/toolchains.xml"}
            ]
            artifacts: [
                "**"
            ]
        },
        {
          name: checkstyle
          type: maven
          dependsOn: compilesource
          javaVersion: jdk-21
          mavenCommands: [
            {goal: "validate", args: "-B -Pcheckstyle --global-toolchains build_config/toolchains.xml"}
          ]
        },
        {
          name: spotbugs
          type: maven
          dependsOn: compilesource
          javaVersion: jdk-21
          mavenCommands: [
            { goal: "validate", args: "-B -Pspotbugs --global-toolchains build_config/toolchains.xml"}
          ]
        },
        {
          name: copyright
          type: maven
          dependsOn: compileplugins
          javaVersion: jdk-21
          mavenCommands: [
            { goal: "validate", args: "-B -Pcopyright --global-toolchains build_config/toolchains.xml"}
          ]
        },
        {
            name: publish_oci_helidon_maven_artifacts
            type: publishmaven
            dependsOn: compilesource
            repository: ${releaseArtifactoryRepo}
            snapshotRepository: ${snapshotArtifactoryRepo}
            multiModuleDeploy: true
        }
    ]
