<project xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"
         xmlns="http://maven.apache.org/POM/4.0.0"
         xsi:schemaLocation="http://maven.apache.org/POM/4.0.0 https://maven.apache.org/xsd/maven-4.0.0.xsd">
    <modelVersion>4.0.0</modelVersion>
    <parent>
        <groupId>com.oracle.helidon.oci</groupId>
        <artifactId>helidon-oci-dependencies</artifactId>
        <version>1.0-SNAPSHOT</version>
        <relativePath>./dependencies/pom.xml</relativePath>
    </parent>

    <artifactId>helidon-oci-project</artifactId>
    <version>1.0-SNAPSHOT</version>
    <packaging>pom</packaging>

    <name>Helidon OCI Pegasus Native Integrations Project</name>

    <properties>
        <maven.compiler.source>11</maven.compiler.source>
        <maven.compiler.target>${maven.compiler.source}</maven.compiler.target>

        <surefire.argLine>-Xmx1024m -Dfile.encoding=UTF-8</surefire.argLine>
        <failsafe.argLine>-Xmx1024m -Dfile.encoding=UTF-8</failsafe.argLine>
        <surefire.coverage.argline />
        <failsafe.coverage.argline />

        <version.lib.commons-io>2.13.0</version.lib.commons-io>
        <version.lib.commons-lang3>3.10</version.lib.commons-lang3>
        <version.lib.hamcrest>1.3</version.lib.hamcrest>
        <version.lib.httpclient>4.5.14</version.lib.httpclient>
        <version.lib.httpcore>4.4.16</version.lib.httpcore>
        <version.lib.guice>5.1.0</version.lib.guice>
        <version.lib.joda-time>2.10.14</version.lib.joda-time>
        <version.lib.javaassist>3.29.2-GA</version.lib.javaassist>
        <version.lib.junit>5.10.1</version.lib.junit>
        <version.lib.mockito>2.23.4</version.lib.mockito>
        <version.lib.nimbus-jose-jwt>9.10.1</version.lib.nimbus-jose-jwt>

        <version.plugin.compiler>3.8.1</version.plugin.compiler>
        <version.plugin.extra-enforcer-rules>1.7.0</version.plugin.extra-enforcer-rules>
        <version.plugin.failsafe>3.0.0-M5</version.plugin.failsafe>
        <version.plugin.helidon-build-tools>2.3.8</version.plugin.helidon-build-tools>
        <version.plugin.lombok-maven-plugin>1.18.20.0</version.plugin.lombok-maven-plugin>
        <version.plugin.surefire>3.0.0-M5</version.plugin.surefire>
        <version.plugin.maven-build-helper-plugin>3.4.0</version.plugin.maven-build-helper-plugin>
        <version.plugin.maven-directory-plugin>1.0</version.plugin.maven-directory-plugin>
        <version.plugin.maven-enforcer-plugin>3.4.1</version.plugin.maven-enforcer-plugin>
        <version.plugin.maven-exec-plugin>3.1.0</version.plugin.maven-exec-plugin>
        <version.plugin.maven-javadoc-plugin>2.10.4</version.plugin.maven-javadoc-plugin>
        <version.plugin.maven-versions-plugin>2.16.1</version.plugin.maven-versions-plugin>
    </properties>

    <modules>
        <module>dependencies</module>
        <module>repackaged-oci</module>
        <module>oci-error-code</module>
        <module>oci-identity</module>
        <module>oci-request-id</module>
        <module>oci-swagger-maven-plugin</module>
        <module>bom</module>
        <module>applications</module>
        <module>integration-tests</module>
    </modules>

    <dependencyManagement>
        <dependencies>
            <dependency>
                <groupId>io.helidon</groupId>
                <artifactId>helidon-dependencies</artifactId>
                <version>${helidon.version}</version>
                <type>pom</type>
                <scope>import</scope>
            </dependency>

            <!-- misc. other 3rd party dependencies -->
            <dependency>
                <groupId>commons-io</groupId>
                <artifactId>commons-io</artifactId>
                <version>${version.lib.commons-io}</version>
            </dependency>
            <dependency>
                <groupId>com.google.inject</groupId>
                <artifactId>guice</artifactId>
                <version>${version.lib.guice}</version>
                <exclusions>
                    <exclusion>
                        <groupId>javax.inject</groupId>
                        <artifactId>javax.inject</artifactId>
                    </exclusion>
                    <exclusion>
                        <groupId>aopalliance</groupId>
                        <artifactId>aopalliance</artifactId>
                    </exclusion>
                </exclusions>
            </dependency>
            <dependency>
                <groupId>com.nimbusds</groupId>
                <artifactId>nimbus-jose-jwt</artifactId>
                <version>${version.lib.nimbus-jose-jwt}</version>
            </dependency>
            <dependency>
                <groupId>joda-time</groupId>
                <artifactId>joda-time</artifactId>
                <version>${version.lib.joda-time}</version>
            </dependency>
            <dependency>
                <groupId>org.apache.commons</groupId>
                <artifactId>commons-lang3</artifactId>
                <version>${version.lib.commons-lang3}</version>
            </dependency>
            <dependency>
                <groupId>org.apache.httpcomponents</groupId>
                <artifactId>httpclient</artifactId>
                <version>${version.lib.httpclient}</version>
            </dependency>
            <dependency>
                <groupId>org.apache.httpcomponents</groupId>
                <artifactId>httpcore</artifactId>
                <version>${version.lib.httpcore}</version>
            </dependency>
            <dependency>
                <groupId>org.hamcrest</groupId>
                <artifactId>hamcrest-all</artifactId>
                <version>${version.lib.hamcrest}</version>
                <scope>test</scope>
            </dependency>
            <dependency>
                <groupId>org.hamcrest</groupId>
                <artifactId>hamcrest-core</artifactId>
                <version>${version.lib.hamcrest}</version>
                <scope>test</scope>
            </dependency>
            <dependency>
                <groupId>org.javassist</groupId>
                <artifactId>javassist</artifactId>
                <version>${version.lib.javaassist}</version>
            </dependency>
            <dependency>
                <groupId>org.junit.jupiter</groupId>
                <artifactId>junit-jupiter-api</artifactId>
                <version>${version.lib.junit}</version>
                <scope>test</scope>
            </dependency>
            <dependency>
                <groupId>org.junit.jupiter</groupId>
                <artifactId>junit-jupiter-params</artifactId>
                <version>${version.lib.junit}</version>
                <scope>test</scope>
            </dependency>
            <dependency>
                <groupId>org.junit.jupiter</groupId>
                <artifactId>junit-jupiter-engine</artifactId>
                <version>${version.lib.junit}</version>
                <scope>test</scope>
            </dependency>
            <dependency>
                <groupId>org.mockito</groupId>
                <artifactId>mockito-core</artifactId>
                <version>${version.lib.mockito}</version>
                <scope>test</scope>
            </dependency>

        </dependencies>
    </dependencyManagement>

    <build>
        <pluginManagement>
            <plugins>
                <plugin>
                    <groupId>org.apache.maven.plugins</groupId>
                    <artifactId>maven-compiler-plugin</artifactId>
                    <version>${version.plugin.compiler}</version>
                </plugin>
                <plugin>
                    <groupId>org.codehaus.mojo</groupId>
                    <artifactId>versions-maven-plugin</artifactId>
                    <version>${version.plugin.maven-versions-plugin}</version>
                </plugin>
                <plugin>
                    <groupId>io.helidon.build-tools</groupId>
                    <artifactId>helidon-services-plugin</artifactId>
                    <version>${version.plugin.helidon-build-tools}</version>
                    <configuration>
                        <mode>fail</mode>
                    </configuration>
                    <executions>
                        <execution>
                            <id>generate-meta-inf-services</id>
                            <phase>compile</phase>
                            <goals>
                                <goal>services</goal>
                            </goals>
                        </execution>
                    </executions>
                </plugin>
                <plugin>
                    <groupId>org.apache.maven.plugins</groupId>
                    <artifactId>maven-enforcer-plugin</artifactId>
                    <version>${version.plugin.maven-enforcer-plugin}</version>
                    <dependencies>
                        <!-- dependencies to your artifact contains rule implementation -->
                        <dependency>
                            <groupId>io.helidon.build-tools</groupId>
                            <artifactId>helidon-build-maven-enforcer-rules</artifactId>
                            <version>${version.plugin.helidon-build-tools}</version>
                        </dependency>
                        <dependency>
                            <groupId>com.oracle.oci.sdk</groupId>
                            <artifactId>oci-java-sdk-enforcer-rules</artifactId>
                            <version>${oci-java-sdk-version}</version>
                            <optional>false</optional>
                        </dependency>
                        <dependency>
                            <groupId>org.codehaus.mojo</groupId>
                            <artifactId>extra-enforcer-rules</artifactId>
                            <version>${version.plugin.extra-enforcer-rules}</version>
                        </dependency>
                    </dependencies>
                    <executions>
                        <execution>
                            <id>enforce-jakarta-dependencies</id>
                            <goals>
                                <goal>enforce</goal>
                            </goals>
                            <configuration>
                                <rules>
                                    <helidonDependenciesRule>
                                        <namespace>JAVAX</namespace>
                                        <excludedGavRegExs>
                                            <excludedGav>javax.servlet:javax.servlet-api:.*</excludedGav>
                                        </excludedGavRegExs>
                                    </helidonDependenciesRule>
                                    <bannedDependencies>
                                        <searchTransitive>true</searchTransitive>
                                        <excludes>
<!--                                            <exclude>bc-fips</exclude>-->
<!--                                            <exclude>bcpkix-fips</exclude>-->
                                            <exclude>io.dropwizard</exclude>
                                            <exclude>com.oracle.pic.commons:service-core</exclude>
                                            <exclude>junit</exclude>
                                            <exclude>lombok</exclude>
                                        </excludes>
                                    </bannedDependencies>
                                    <!-- TODO: https://bitbucket.oci.oraclecorp.com/projects/SDK/repos/java-sdk/pull-requests/5217/overview -->
                                    <noMixedOciJavaSdkVersionsRule implementation="com.oracle.bmc.enforcer.rule.NoMixedOciJavaSdkVersionsRule">
                                        <allowedDependencies>
                                            <allowedDependency>com.oracle.oci.sdk:oci-java-sdk-common:.*</allowedDependency>
                                            <allowedDependency>com.oracle.oci.sdk:oci-java-sdk-circuitbreaker:.*</allowedDependency>
                                            <allowedDependency>com.oracle.oci.sdk:oci-java-sdk-common-httpclient:.*</allowedDependency>
                                            <allowedDependency>com.oracle.oci.sdk:oci-java-sdk-objectstorage-generated:.*</allowedDependency>
                                        </allowedDependencies>
                                    </noMixedOciJavaSdkVersionsRule>
                                    <!-- https://maven.apache.org/enforcer/enforcer-rules/dependencyConvergence.html -->
                                    <DependencyConvergence/>
                                    <!-- https://www.mojohaus.org/extra-enforcer-rules/banDuplicateClasses.html -->
                                    <banDuplicateClasses>
                                        <scopes>
                                            <scope>compile</scope>
                                        </scopes>
                                        <findAllDuplicates>true</findAllDuplicates>
                                        <ignoreWhenIdentical>true</ignoreWhenIdentical>
                                    </banDuplicateClasses>
                                </rules>
                            </configuration>
                        </execution>
                    </executions>
                </plugin>
                <plugin>
                    <groupId>org.commonjava.maven.plugins</groupId>
                    <artifactId>directory-maven-plugin</artifactId>
                    <version>${version.plugin.maven-directory-plugin}</version>
                </plugin>
                <plugin>
                    <groupId>org.codehaus.mojo</groupId>
                    <artifactId>exec-maven-plugin</artifactId>
                    <version>${version.plugin.maven-exec-plugin}</version>
                </plugin>
                <plugin>
                    <groupId>org.codehaus.mojo</groupId>
                    <artifactId>build-helper-maven-plugin</artifactId>
                    <version>${version.plugin.maven-build-helper-plugin}</version>
                </plugin>
                <plugin>
                    <groupId>org.apache.maven.plugins</groupId>
                    <artifactId>maven-surefire-plugin</artifactId>
                    <version>${version.plugin.surefire}</version>
                    <configuration>
                        <useModulePath>false</useModulePath>
                        <trimStackTrace>false</trimStackTrace>
                        <!-- DO NOT override argLine instead use surefire.argLine -->
                        <argLine>${surefire.argLine} ${surefire.coverage.argline}</argLine>
                        <redirectTestOutputToFile>true</redirectTestOutputToFile>
                    </configuration>
                </plugin>
                <plugin>
                    <groupId>org.apache.maven.plugins</groupId>
                    <artifactId>maven-failsafe-plugin</artifactId>
                    <version>${version.plugin.failsafe}</version>
                    <configuration>
                        <useModulePath>false</useModulePath>
                        <!-- DO NOT override argLine instead use failsafe.argLine -->
                        <argLine>${failsafe.argLine} ${failsafe.coverage.argline}</argLine>
                        <redirectTestOutputToFile>true</redirectTestOutputToFile>
                    </configuration>
                </plugin>
            </plugins>
        </pluginManagement>
        <plugins>
            <plugin>
                <groupId>org.commonjava.maven.plugins</groupId>
                <artifactId>directory-maven-plugin</artifactId>
                <executions>
                    <execution>
                        <id>generate-top-parent-basedir</id>
                        <goals>
                            <goal>highest-basedir</goal>
                        </goals>
                        <phase>validate</phase>
                        <configuration>
                            <property>top.parent.basedir</property>
                        </configuration>
                    </execution>
                </executions>
            </plugin>
        </plugins>
    </build>

    <repositories>
        <repository>
            <id>libs-release</id>
            <name>Libs release in Artifactory</name>
            <url>https://artifactory.oci.oraclecorp.com/libs-release</url>
        </repository>
    </repositories>
    <pluginRepositories>
        <pluginRepository>
            <id>libs-release</id>
            <name>Libs release in Artifactory</name>
            <url>https://artifactory.oci.oraclecorp.com/libs-release</url>
        </pluginRepository>
    </pluginRepositories>
</project>
