<?xml version="1.0" encoding="UTF-8"?>
<!--
    Copyright (c) 2023, 2024 Oracle and/or its affiliates.
-->

<project xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"
        xmlns="http://maven.apache.org/POM/4.0.0"
        xsi:schemaLocation="http://maven.apache.org/POM/4.0.0 https://maven.apache.org/xsd/maven-4.0.0.xsd">
    <modelVersion>4.0.0</modelVersion>
    <parent>
        <groupId>com.oracle.helidon.oci</groupId>
        <artifactId>helidon-oci-dependencies</artifactId>
        <version>1.0.0-SNAPSHOT</version>
        <relativePath>./dependencies/pom.xml</relativePath>
    </parent>

    <artifactId>helidon-oci-project</artifactId>
    <version>1.0.0-SNAPSHOT</version>
    <packaging>pom</packaging>

    <name>Helidon OCI Project</name>

    <properties>
        <maven.compiler.source>21</maven.compiler.source>
        <maven.compiler.target>${maven.compiler.source}</maven.compiler.target>

        <project.build.sourceEncoding>UTF-8</project.build.sourceEncoding>
        <project.reporting.outputEncoding>UTF-8</project.reporting.outputEncoding>

        <surefire.argLine>-Xmx1024m -Dfile.encoding=UTF-8</surefire.argLine>
        <failsafe.argLine>-Xmx1024m -Dfile.encoding=UTF-8</failsafe.argLine>
        <surefire.coverage.argline/>
        <failsafe.coverage.argline/>

        <spotbugs.skip>false</spotbugs.skip>
        <spotbugs.threshold>Medium</spotbugs.threshold>

        <checkstyle.skip>false</checkstyle.skip>

        <version.lib.checkstyle>10.12.5</version.lib.checkstyle>
        <version.lib.hamcrest>1.3</version.lib.hamcrest>
        <version.lib.junit>5.10.1</version.lib.junit>
        <version.lib.mockito>2.23.4</version.lib.mockito>

        <version.plugin.checkstyle>3.3.1</version.plugin.checkstyle>
        <version.plugin.compiler>3.11.0</version.plugin.compiler>
        <version.plugin.extra-enforcer-rules>1.7.0</version.plugin.extra-enforcer-rules>
        <version.plugin.failsafe>3.1.2</version.plugin.failsafe>
        <version.plugin.helidon-build-tools>4.0.9</version.plugin.helidon-build-tools>
        <version.plugin.surefire>3.1.0</version.plugin.surefire>
        <version.plugin.shade>3.5.1</version.plugin.shade>
        <version.plugin.spotbugs>4.7.3.5</version.plugin.spotbugs>
        <version.plugin.findsecbugs>1.12.0</version.plugin.findsecbugs>
        <version.plugin.maven-build-helper-plugin>3.4.0</version.plugin.maven-build-helper-plugin>
        <version.plugin.maven-directory-plugin>1.0</version.plugin.maven-directory-plugin>
        <version.plugin.maven-enforcer-plugin>3.4.1</version.plugin.maven-enforcer-plugin>
        <version.plugin.maven-exec-plugin>3.1.0</version.plugin.maven-exec-plugin>
        <version.plugin.maven-jar-plugin>3.3.0</version.plugin.maven-jar-plugin>
        <version.plugin.maven-versions-plugin>2.16.1</version.plugin.maven-versions-plugin>
    </properties>

    <modules>
        <module>parent</module>
        <module>bom</module>
        <module>dependencies</module>
        <module>common</module>
        <module>repackaged-oci</module>
        <module>metrics</module>
        <module>secret-service</module>
        <module>splat</module>
        <module>swagger-maven-plugin</module>
        <module>applications</module>
        <module>tests</module>
    </modules>

    <dependencyManagement>
        <dependencies>
            <dependency>
                <groupId>io.helidon</groupId>
                <artifactId>helidon-dependencies</artifactId>
                <version>${helidon.version}</version>
                <type>pom</type>
                <scope>import</scope>
            </dependency>

            <dependency>
                <groupId>io.helidon.microprofile.testing</groupId>
                <artifactId>helidon-microprofile-testing-junit5</artifactId>
                <version>${helidon.version}</version>
            </dependency>

            <!-- misc. other 3rd party dependencies -->
            <dependency>
                <groupId>org.hamcrest</groupId>
                <artifactId>hamcrest-all</artifactId>
                <version>${version.lib.hamcrest}</version>
                <scope>test</scope>
            </dependency>
            <dependency>
                <groupId>org.hamcrest</groupId>
                <artifactId>hamcrest-core</artifactId>
                <version>${version.lib.hamcrest}</version>
                <scope>test</scope>
            </dependency>
            <dependency>
                <groupId>org.junit.jupiter</groupId>
                <artifactId>junit-jupiter-api</artifactId>
                <version>${version.lib.junit}</version>
                <scope>test</scope>
            </dependency>
            <dependency>
                <groupId>org.junit.jupiter</groupId>
                <artifactId>junit-jupiter-params</artifactId>
                <version>${version.lib.junit}</version>
                <scope>test</scope>
            </dependency>
            <dependency>
                <groupId>org.junit.jupiter</groupId>
                <artifactId>junit-jupiter-engine</artifactId>
                <version>${version.lib.junit}</version>
                <scope>test</scope>
            </dependency>
            <dependency>
                <groupId>org.mockito</groupId>
                <artifactId>mockito-core</artifactId>
                <version>${version.lib.mockito}</version>
                <scope>test</scope>
            </dependency>
        </dependencies>
    </dependencyManagement>

    <build>
        <pluginManagement>
            <plugins>
                <plugin>
                    <groupId>org.apache.maven.plugins</groupId>
                    <artifactId>maven-compiler-plugin</artifactId>
                    <version>${version.plugin.compiler}</version>
                </plugin>
                <plugin>
                    <groupId>org.codehaus.mojo</groupId>
                    <artifactId>versions-maven-plugin</artifactId>
                    <version>${version.plugin.maven-versions-plugin}</version>
                </plugin>
                <plugin>
                    <groupId>org.apache.maven.plugins</groupId>
                    <artifactId>maven-enforcer-plugin</artifactId>
                    <version>${version.plugin.maven-enforcer-plugin}</version>
                    <dependencies>
                        <!-- dependencies to your artifact contains rule implementation -->
                        <dependency>
                            <groupId>io.helidon.build-tools</groupId>
                            <artifactId>helidon-build-maven-enforcer-rules</artifactId>
                            <version>${version.plugin.helidon-build-tools}</version>
                        </dependency>
                        <dependency>
                            <groupId>com.oracle.oci.sdk</groupId>
                            <artifactId>oci-java-sdk-enforcer-rules</artifactId>
                            <version>${oci-java-sdk-version}</version>
                            <optional>false</optional>
                        </dependency>
                        <dependency>
                            <groupId>org.codehaus.mojo</groupId>
                            <artifactId>extra-enforcer-rules</artifactId>
                            <version>${version.plugin.extra-enforcer-rules}</version>
                        </dependency>
                    </dependencies>
                    <executions>
                        <execution>
                            <id>enforce-jakarta-dependencies</id>
                            <goals>
                                <goal>enforce</goal>
                            </goals>
                            <configuration>
                                <rules>
                                    <helidonDependenciesRule>
                                        <namespace>JAKARTA</namespace>
                                        <excludedGavRegExs>
                                            <excludedGav>jakarta.servlet:jakarta.servlet-api:.*</excludedGav>
                                            <excludedGav>jakarta.el:jakarta.el-api:.*</excludedGav>
                                            <excludedGav>javax.ws.rs:javax.ws.rs-api:.*</excludedGav>
                                        </excludedGavRegExs>
                                    </helidonDependenciesRule>
                                    <bannedDependencies>
                                        <searchTransitive>true</searchTransitive>
                                        <excludes>
                                            <exclude>io.dropwizard</exclude>
                                            <exclude>com.oracle.pic.commons:service-core</exclude>
                                            <exclude>junit</exclude>
                                            <exclude>lombok</exclude>
                                        </excludes>
                                    </bannedDependencies>
                                    <noMixedOciJavaSdkVersionsRule
                                            implementation="com.oracle.bmc.enforcer.rule.NoMixedOciJavaSdkVersionsRule">
                                        <allowedDependencies>
                                            <allowedDependency>com.oracle.oci.sdk:oci-java-sdk-common:*</allowedDependency>
                                            <allowedDependency>com.oracle.oci.sdk:oci-java-sdk-circuitbreaker:*
                                            </allowedDependency>
                                            <allowedDependency>com.oracle.oci.sdk:oci-java-sdk-common-httpclient:*
                                            </allowedDependency>
                                            <allowedDependency>com.oracle.oci.sdk:oci-java-sdk-objectstorage-generated:*
                                            </allowedDependency>
                                        </allowedDependencies>
                                    </noMixedOciJavaSdkVersionsRule>
                                    <!-- https://maven.apache.org/enforcer/enforcer-rules/dependencyConvergence.html -->
                                    <DependencyConvergence/>
                                    <!-- https://www.mojohaus.org/extra-enforcer-rules/banDuplicateClasses.html -->
                                    <banDuplicateClasses>
                                        <scopes>
                                            <scope>compile</scope>
                                        </scopes>
                                        <findAllDuplicates>true</findAllDuplicates>
                                        <ignoreWhenIdentical>true</ignoreWhenIdentical>
                                    </banDuplicateClasses>
                                </rules>
                            </configuration>
                        </execution>
                    </executions>
                </plugin>
                <plugin>
                    <groupId>org.commonjava.maven.plugins</groupId>
                    <artifactId>directory-maven-plugin</artifactId>
                    <version>${version.plugin.maven-directory-plugin}</version>
                </plugin>
                <plugin>
                    <groupId>org.codehaus.mojo</groupId>
                    <artifactId>exec-maven-plugin</artifactId>
                    <version>${version.plugin.maven-exec-plugin}</version>
                </plugin>
                <plugin>
                    <groupId>org.codehaus.mojo</groupId>
                    <artifactId>build-helper-maven-plugin</artifactId>
                    <version>${version.plugin.maven-build-helper-plugin}</version>
                </plugin>
                <plugin>
                    <groupId>org.apache.maven.plugins</groupId>
                    <artifactId>maven-surefire-plugin</artifactId>
                    <version>${version.plugin.surefire}</version>
                    <configuration>
                        <useModulePath>false</useModulePath>
                        <trimStackTrace>false</trimStackTrace>
                        <!-- DO NOT override argLine instead use surefire.argLine -->
                        <argLine>${surefire.argLine} ${surefire.coverage.argline}</argLine>
                        <redirectTestOutputToFile>true</redirectTestOutputToFile>
                    </configuration>
                </plugin>
                <plugin>
                    <groupId>org.apache.maven.plugins</groupId>
                    <artifactId>maven-failsafe-plugin</artifactId>
                    <version>${version.plugin.failsafe}</version>
                    <configuration>
                        <useModulePath>false</useModulePath>
                        <!-- DO NOT override argLine instead use failsafe.argLine -->
                        <argLine>${failsafe.argLine} ${failsafe.coverage.argline}</argLine>
                        <redirectTestOutputToFile>true</redirectTestOutputToFile>
                    </configuration>
                </plugin>
                <plugin>
                    <groupId>org.apache.maven.plugins</groupId>
                    <artifactId>maven-shade-plugin</artifactId>
                    <version>${version.plugin.shade}</version>
                </plugin>
                <plugin>
                    <groupId>org.apache.maven.plugins</groupId>
                    <artifactId>maven-jar-plugin</artifactId>
                    <version>${version.plugin.maven-jar-plugin}</version>
                    <configuration>
                        <archive>
                            <manifest>
                                <addDefaultImplementationEntries>true</addDefaultImplementationEntries>
                            </manifest>
                            <manifestEntries>
                                <Implementation-URL>https://helidon.io</Implementation-URL>
                            </manifestEntries>
                        </archive>
                    </configuration>
                </plugin>
                <plugin>
                    <groupId>org.apache.maven.plugins</groupId>
                    <artifactId>maven-checkstyle-plugin</artifactId>
                    <version>${version.plugin.checkstyle}</version>
                    <configuration>
                        <skip>${checkstyle.skip}</skip>
                        <sourceDirectories>
                            <sourceDirectory>${project.build.sourceDirectory}</sourceDirectory>
                        </sourceDirectories>
                    </configuration>
                    <dependencies>
                        <dependency>
                            <groupId>com.puppycrawl.tools</groupId>
                            <artifactId>checkstyle</artifactId>
                            <version>${version.lib.checkstyle}</version>
                            <exclusions>
                                <exclusion>
                                    <groupId>com.sun</groupId>
                                    <artifactId>tools</artifactId>
                                </exclusion>
                            </exclusions>
                        </dependency>
                    </dependencies>
                </plugin>
                <plugin>
                    <groupId>com.github.spotbugs</groupId>
                    <artifactId>spotbugs-maven-plugin</artifactId>
                    <version>${version.plugin.spotbugs}</version>
                    <configuration>
                        <omitVisitors>FindReturnRef</omitVisitors>
                        <skip>${spotbugs.skip}</skip>
                        <threshold>${spotbugs.threshold}</threshold>
                        <!--suppress UnresolvedMavenProperty -->
                        <excludeFilterFile>${spotbugs.exclude}</excludeFilterFile>
                        <xmlOutput>true</xmlOutput>
                        <plugins>
                            <plugin>
                                <groupId>com.h3xstream.findsecbugs</groupId>
                                <artifactId>findsecbugs-plugin</artifactId>
                                <version>${version.plugin.findsecbugs}</version>
                            </plugin>
                        </plugins>
                    </configuration>
                </plugin>
                <plugin>
                    <groupId>io.helidon.build-tools</groupId>
                    <artifactId>helidon-enforcer-plugin</artifactId>
                    <version>${version.plugin.helidon-build-tools}</version>
                    <configuration>
                        <rules>
                            <rule>copyright</rule>
                            <rule>typos</rule>
                        </rules>
                        <copyrightConfig>
                            <failOnError>true</failOnError>
                            <!--suppress UnresolvedMavenProperty -->
                            <templateFile>${top.parent.basedir}/etc/copyright.txt</templateFile>
                            <!--suppress UnresolvedMavenProperty -->
                            <excludeFile>${top.parent.basedir}/etc/copyright-exclude.txt</excludeFile>
                        </copyrightConfig>
                        <typosConfig>
                            <failOnError>true</failOnError>
                            <typos>
                                <typo>heldion</typo>
                                <typo>helidion</typo>
                                <typo>buidler</typo>
                                <typo>vuilder</typo>
                                <typo>bidler</typo>
                                <typo>microrpofile</typo>
                                <typo>depenedency</typo>
                                <typo>configuraiton</typo>
                                <typo>Respnose</typo>
                            </typos>
                        </typosConfig>
                    </configuration>
                </plugin>
            </plugins>
        </pluginManagement>
        <plugins>
            <plugin>
                <groupId>org.commonjava.maven.plugins</groupId>
                <artifactId>directory-maven-plugin</artifactId>
                <executions>
                    <execution>
                        <id>generate-top-parent-basedir</id>
                        <goals>
                            <goal>highest-basedir</goal>
                        </goals>
                        <phase>validate</phase>
                        <configuration>
                            <property>top.parent.basedir</property>
                        </configuration>
                    </execution>
                </executions>
            </plugin>
        </plugins>
    </build>
    <profiles>
        <profile>
            <id>spotbugs</id>
            <build>
                <plugins>
                    <plugin>
                        <groupId>com.github.spotbugs</groupId>
                        <artifactId>spotbugs-maven-plugin</artifactId>
                        <executions>
                            <execution>
                                <goals>
                                    <goal>check</goal>
                                </goals>
                            </execution>
                        </executions>
                    </plugin>
                </plugins>
            </build>
        </profile>
        <profile>
            <id>checkstyle</id>
            <build>
                <plugins>
                    <plugin>
                        <groupId>org.apache.maven.plugins</groupId>
                        <artifactId>maven-checkstyle-plugin</artifactId>
                        <executions>
                            <execution>
                                <id>run-checkstyle</id>
                                <goals>
                                    <goal>check</goal>
                                </goals>
                                <phase>validate</phase>
                                <configuration>
                                    <!--suppress UnresolvedMavenProperty -->
                                    <configLocation>${top.parent.basedir}/etc/checkstyle.xml</configLocation>
                                    <!--suppress UnresolvedMavenProperty -->
                                    <suppressionsLocation>${top.parent.basedir}/etc/checkstyle-suppressions.xml
                                    </suppressionsLocation>
                                </configuration>
                            </execution>
                        </executions>
                    </plugin>
                </plugins>
            </build>
        </profile>
        <profile>
            <id>copyright</id>
            <build>
                <plugins>
                    <plugin>
                        <groupId>io.helidon.build-tools</groupId>
                        <artifactId>helidon-enforcer-plugin</artifactId>
                        <executions>
                            <execution>
                                <id>helidon-enforcer</id>
                                <phase>validate</phase>
                                <goals>
                                    <goal>check</goal>
                                </goals>
                            </execution>
                        </executions>
                    </plugin>
                </plugins>
            </build>
        </profile>
    </profiles>
    <repositories>
        <repository>
            <id>libs-release</id>
            <name>Libs release in Artifactory</name>
            <url>https://artifactory.oci.oraclecorp.com/libs-release</url>
        </repository>
    </repositories>
    <pluginRepositories>
        <pluginRepository>
            <id>libs-release</id>
            <name>Libs release in Artifactory</name>
            <url>https://artifactory.oci.oraclecorp.com/libs-release</url>
        </pluginRepository>
    </pluginRepositories>
</project>
