<?xml version="1.0" encoding="UTF-8"?>
<!--
    Copyright (c) 2023, 2026 Oracle and/or its affiliates.
-->

<project xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance" xmlns="http://maven.apache.org/POM/4.0.0"
        xsi:schemaLocation="http://maven.apache.org/POM/4.0.0 https://maven.apache.org/xsd/maven-4.0.0.xsd">
    <modelVersion>4.0.0</modelVersion>
    <parent>
        <groupId>io.helidon.applications</groupId>
        <artifactId>helidon-se</artifactId>
        <version>4.4.0-M2</version>
        <relativePath/>
    </parent>

    <groupId>com.oracle.helidon.oci</groupId>
    <artifactId>helidon-oci-se</artifactId>
    <version>2.0.0-SNAPSHOT</version>
    <packaging>pom</packaging>

    <name>Helidon OCI SE Applications</name>
    <description>Helidon OCI SE applications</description>

    <properties>
        <helidon.oci.version>2.0.0-SNAPSHOT</helidon.oci.version>
        <version.lib.guava>33.3.1-jre</version.lib.guava>
        <jersey-lib-version>2.47</jersey-lib-version>
    </properties>

    <dependencyManagement>
        <dependencies>
            <dependency>
                <groupId>com.oracle.helidon.oci</groupId>
                <artifactId>helidon-oci-dependencies</artifactId>
                <version>${helidon.oci.version}</version>
                <type>pom</type>
                <scope>import</scope>
            </dependency>
            <!-- The following override versions in parent pom -->
            <dependency>
                <groupId>org.glassfish.jersey.core</groupId>
                <artifactId>jersey-client</artifactId>
                <version>${jersey-lib-version}</version>
            </dependency>
        </dependencies>
    </dependencyManagement>

</project>
