/*
 * Copyright (c) 2023, 2025 Oracle and/or its affiliates.
 */
package com.oracle.helidon.oci.common.requestid;

import com.oracle.pic.commons.rid.RequestIdUtils;

import static com.oracle.helidon.oci.common.requestid.OciRequestIdImpl.DELIMITER;

/**
 * OCI request ID.
 * <p>
 * The id is formed from three sections:
 * <ul>
 *     <li>customerId - optional customer id, if not provided, it is an empty string</li>
 *     <li>traceId - trace id is either received from upstream service, or is generated</li>
 *     <li>spanId - span id is always generated for a service invocation, and returned to caller</li>
 * </ul>
 * This id can be obtained from {@code io.helidon.common.context.Context} if enabled (always true
 * for Helidon MP).
 * It can also be created from request/response header using appropriate parse method.
 */
public interface OciRequestId {
    /**
     * Name of the OCI request ID header, and key under which we store it in the {@link io.helidon.logging.common.HelidonMdc}.
     */
    String OCI_REQUEST_ID = RequestIdUtils.OPC_REQUEST_ID_HEADER;

    /**
     * Parse the upstream request header.
     * <p>
     * Strips invalid characters, truncates too long, and handles invalid content per requirements in OCI.
     * This method may log warnings under logger named as this class for invalid requests. This is a requirement
     * of the OCI infrastructure. If this is not desired (i.e. if the service is open to public and may receive
     * intentional bad requests that would pollute the log files), disable the logger.
     *
     * @param headerValue value of the header (expects one to two segments)
     * @return parsed request id, generates trace id if not present, generates span id
     */
    static OciRequestId parseUpstreamRequest(String headerValue) {
        return OciRequestIdImpl.parseUpstreamRequest(headerValue);
    }

    /**
     * Parse the downstream response header.
     * <p>
     * Strips invalid characters, truncates too long, and handles invalid content per requirements in OCI.
     * This method may log warnings under logger named as this class for invalid requests. This is a requirement
     * of the OCI infrastructure. If this is not desired (i.e. if the service is open to public and may receive
     * intentional bad requests that would pollute the log files), disable the logger.
     *
     * @param requestId   to use if the response id is invalid (only customer id and trace id would be used, span id would be
     *                    empty)
     * @param headerValue value of the header (expects one to three segments)
     * @return parsed request id, generates trace id and span id if not present
     */
    static OciRequestId parseDownstreamResponse(OciRequestId requestId, String headerValue) {
        return OciRequestIdImpl.parseDownstreamResponse(requestId, headerValue);
    }

    /**
     * Generate a new request id.
     *
     * @return a generated trace id and span id, with empty customer id
     */
    static OciRequestId generate() {
        return OciRequestIdImpl.generate();
    }

    /**
     * Customer ID. This may be an empty string if customer does not provide a request id.
     *
     * @return customer id, never null
     */
    String customerId();

    /**
     * Trace ID generated by the first service receiving this request.
     *
     * @return trace ID of this request
     */
    String traceId();

    /**
     * Span ID generated by each service, returned in the response.
     * Request header should not contain a spanId, responses must contain spanId.
     *
     * @return span ID of this response header
     */
    String spanId();

    /**
     * Creates the header value to be sent as a response to upstream services.
     *
     * @return slash separated segments for response header to our client
     */
    default String upstreamHeaderValue() {
        return customerId() + DELIMITER
                + traceId() + DELIMITER
                + spanId();
    }

    /**
     * Creates a request value without a span id to send to downstream services.
     *
     * @return slash separated segments for request headers where we are the client
     */
    default String downstreamHeaderValue() {
        return customerId() + DELIMITER
                + traceId();
    }
}
