<?xml version="1.0" encoding="UTF-8"?>
<!--
    Copyright (c) 2024, 2025 Oracle and/or its affiliates.
-->
<project xmlns="http://maven.apache.org/POM/4.0.0"
        xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"
        xsi:schemaLocation="http://maven.apache.org/POM/4.0.0 https://maven.apache.org/xsd/maven-4.0.0.xsd">
    <modelVersion>4.0.0</modelVersion>
    <parent>
        <groupId>com.oracle.helidon.oci</groupId>
        <artifactId>helidon-repackaged-oci</artifactId>
        <version>1.2.0-SNAPSHOT</version>
        <relativePath>../pom.xml</relativePath>
    </parent>
    <artifactId>helidon-repackaged-oci-authentication-client</artifactId>
    <version>1.2.0-SNAPSHOT</version>
    <packaging>jar</packaging>

    <name>Helidon OCI Repackaged OCI authentication-client</name>

    <properties>
        <spotbugs.skip>true</spotbugs.skip>
        <specPath>${processed-spec-dir}</specPath>
        <swagger-dir>${project.basedir}/src/main/java/com/oracle/pic/identity/authentication/swagger</swagger-dir>
        <spec-dir>${swagger-dir}/specs</spec-dir>
        <enabled-groups-dir>${swagger-dir}/enabled-conditional-groups</enabled-groups-dir>
        <spec-file-name>api.cond.yaml</spec-file-name>
        <processed-spec-dir>${project.build.directory}/classes/internal/api.yaml</processed-spec-dir>
        <codegen.base.package.name>com.oracle.pic.identity.authenticationYYY</codegen.base.package.name>
        <codegen.endpoint>example</codegen.endpoint>
        <codegen.generate.waiters>true</codegen.generate.waiters>
        <codegen.generate.paginators>true</codegen.generate.paginators>
        <codegen.specGenerationType>INTERNAL</codegen.specGenerationType>
        <codegen.is.expect.100.continue.supported>false</codegen.is.expect.100.continue.supported>
    </properties>

    <dependencies>
        <!-- https://bitbucket.oci.oraclecorp.com/projects/IDENT/repos/authorization-sdk/browse/authentication-client -->
        <dependency>
            <groupId>com.oracle.pic.identity.authentication</groupId>
            <artifactId>authentication-client</artifactId>
            <scope>provided</scope>
        </dependency>
        <dependency>
            <groupId>com.oracle.helidon.oci</groupId>
            <artifactId>helidon-oci-javax-shim</artifactId>
            <exclusions>
                <exclusion>
                    <groupId>com.oracle.oci.sdk</groupId>
                    <artifactId>oci-java-sdk-common-httpclient</artifactId>
                </exclusion>
            </exclusions>
        </dependency>
        <dependency>
            <groupId>javax.ws.rs</groupId>
            <artifactId>javax.ws.rs-api</artifactId>
        </dependency>
        <dependency>
            <groupId>com.oracle.oci.sdk</groupId>
            <artifactId>oci-java-sdk-addons-apache-configurator-jersey3</artifactId>
        </dependency>
        <dependency>
            <groupId>jakarta.annotation</groupId>
            <artifactId>jakarta.annotation-api</artifactId>
        </dependency>
        <dependency>
            <groupId>com.oracle.pic.commons</groupId>
            <artifactId>jwt</artifactId>
            <version>1.0.6</version>
        </dependency>
        <dependency>
            <groupId>com.oracle.pic.commons</groupId>
            <artifactId>core</artifactId>
            <exclusions>
                <exclusion>
                    <groupId>jakarta.xml.bind</groupId>
                    <artifactId>jakarta.xml.bind-api</artifactId>
                </exclusion>
                <exclusion>
                    <groupId>javax.ws.rs</groupId>
                    <artifactId>javax.ws.rs-api</artifactId>
                </exclusion>
            </exclusions>
        </dependency>
        <dependency>
            <groupId>com.oracle.oci.sdk</groupId>
            <artifactId>oci-java-sdk-common</artifactId>
            <exclusions>
                <exclusion>
                    <groupId>org.glassfish.jersey.core</groupId>
                    <artifactId>jersey-common</artifactId>
                </exclusion>
                <exclusion>
                    <groupId>com.fasterxml.jackson.core</groupId>
                    <artifactId>jackson-core</artifactId>
                </exclusion>
                <exclusion>
                    <groupId>com.fasterxml.jackson.module</groupId>
                    <artifactId>jackson-module-jaxb-annotations</artifactId>
                </exclusion>
                <exclusion>
                    <groupId>org.bouncycastle</groupId>
                    <artifactId>bcprov-jdk15on</artifactId>
                </exclusion>
                <exclusion>
                    <groupId>org.bouncycastle</groupId>
                    <artifactId>bcprov-jdk15to18</artifactId>
                </exclusion>
                <exclusion>
                    <groupId>org.bouncycastle</groupId>
                    <artifactId>bcpkix-jdk15on</artifactId>
                </exclusion>
                <exclusion>
                    <groupId>org.bouncycastle</groupId>
                    <artifactId>bcpkix-jdk15to18</artifactId>
                </exclusion>
                <exclusion>
                    <artifactId>jersey-client</artifactId>
                    <groupId>org.glassfish.jersey.core</groupId>
                </exclusion>
                <exclusion>
                    <groupId>org.glassfish.jersey.connectors</groupId>
                    <artifactId>jersey-apache-connector</artifactId>
                </exclusion>
            </exclusions>
        </dependency>
        <dependency>
            <groupId>com.fasterxml.jackson.core</groupId>
            <artifactId>jackson-annotations</artifactId>
        </dependency>
        <dependency>
            <groupId>com.google.http-client</groupId>
            <artifactId>google-http-client</artifactId>
        </dependency>
        <dependency>
            <groupId>com.oracle.pic.commons</groupId>
            <artifactId>core-resources</artifactId>
        </dependency>
        <dependency>
            <groupId>org.apache.httpcomponents</groupId>
            <artifactId>httpclient</artifactId>
        </dependency>
        <dependency> <!-- Used for Network test dependencies -->
            <groupId>org.glassfish.jersey.core</groupId>
            <artifactId>jersey-common</artifactId>
            <exclusions>
                <exclusion>
                    <groupId>jakarta.annotation</groupId>
                    <artifactId>jakarta.annotation</artifactId>
                </exclusion>
                <exclusion>
                    <groupId>jakarta.annotation</groupId>
                    <artifactId>jakarta.annotation-api</artifactId>
                </exclusion>
            </exclusions>
        </dependency>
        <dependency>
            <groupId>org.slf4j</groupId>
            <artifactId>slf4j-api</artifactId>
        </dependency>
        <dependency>
            <groupId>joda-time</groupId>
            <artifactId>joda-time</artifactId>
        </dependency>
        <dependency>
            <groupId>com.oracle.oci.sdk</groupId>
            <artifactId>oci-java-sdk-common-httpclient-jersey3</artifactId>
            <version>${oci-java-sdk-version}</version>
            <scope>provided</scope>
        </dependency>


        <dependency>
            <groupId>org.junit.jupiter</groupId>
            <artifactId>junit-jupiter-api</artifactId>
            <scope>test</scope>
        </dependency>
    </dependencies>

    <build>
        <plugins>
            <plugin>
                <groupId>org.codehaus.mojo</groupId>
                <artifactId>build-helper-maven-plugin</artifactId>
                <executions>
                    <execution>
                        <phase>generate-sources</phase>
                        <goals>
                            <goal>add-source</goal>
                        </goals>
                        <configuration>
                            <sources>
                                <source>${project.build.directory}/generated-sources</source>
                            </sources>
                        </configuration>
                    </execution>
                </executions>
            </plugin>

            <plugin>
                <groupId>com.oracle.helidon.oci</groupId>
                <artifactId>helidon-oci-repackage-plugin</artifactId>
                <version>1.2.0-SNAPSHOT</version>
                <executions>
                    <execution>
                        <goals>
                            <goal>repackage-oci-libs</goal>
                        </goals>
                    </execution>
                </executions>
                <configuration>
                    <artifacts>
                        <artifact>
                            <groupId>com.oracle.pic.identity.authentication</groupId>
                            <artifactId>authentication-client</artifactId>
                            <exclusions>
                                <!-- Drop original swagger generated content -->
                                <exclusion>com/oracle/pic/identity/authentication/SessionTokenClient.class</exclusion>
                                <exclusion>com/oracle/pic/identity/authentication/SessionToken*\.class</exclusion>
                                <exclusion>com/oracle/pic/identity/authentication/AuthNSdkAPI*\.class</exclusion>
                                <exclusion>com/oracle/pic/identity/authentication/OauthExchangeToken*\.class</exclusion>
                                <exclusion>com/oracle/pic/identity/authentication/OnBehalfOfToken*\.class</exclusion>
                                <exclusion>com/oracle/pic/identity/authentication/ResourceFederationAPI*\.class</exclusion>
                                <exclusion>com/oracle/pic/identity/authentication/requests/[^/]*\.class</exclusion>
                                <exclusion>com/oracle/pic/identity/authentication/responses/[^/]*\.class</exclusion>
<!--                                <exclusion>com/oracle/pic/identity/authentication/[^/]*\.class</exclusion>-->
                            </exclusions>
                        </artifact>
                    </artifacts>
                    <classes>
                        <class>
                            <name>X509FederationClient</name>
                            <pkg>com.oracle.pic.identity.authentication</pkg>
                            <changes>
                                <change>
                                    <params>
                                        <param>java.lang.String</param>
                                        <param>com.oracle.pic.identity.authentication.key.X509CertificateChainSupplier</param>
                                        <param>com.oracle.pic.identity.authentication.key.X509CertificateChainReloader</param>
                                        <param>com.oracle.pic.identity.authentication.key.SessionKeySupplier</param>
                                        <param>int</param>
                                        <param>com.oracle.pic.identity.authentication.entities.X509FederationRequest$Purpose</param>
                                        <param>java.lang.String</param>
                                        <param>com.oracle.pic.identity.authentication.metrics.AuthMetrics</param>
                                        <param>int</param>
                                        <param>com.oracle.pic.commons.ssl.DynamicSslContextProviderConfig</param>
                                        <param>java.util.Optional</param>
                                    </params>
                                    <substitutions>
                                        <substitution>
                                            <methodCall>com.oracle.bmc.http.internal.RestClientFactory#getObjectMapper</methodCall>
                                            <replacement>
                                                $_ = com.oracle.bmc.serialization.jackson.JacksonSerializer.getDefaultObjectMapper();
                                            </replacement>
                                        </substitution>
                                    </substitutions>
                                </change>
                            </changes>
                        </class>
                    </classes>
                </configuration>
            </plugin>
            <plugin>
                <groupId>com.oracle.bmc.sdk</groupId>
                <artifactId>bmc-sdk-swagger-maven-plugin</artifactId>
                <version>2.70</version>
                <executions>
                    <execution>
                        <goals>
                            <goal>generate</goal>
                        </goals>
                        <phase>generate-sources</phase>
                        <configuration>
                            <specPath>${project.build.directory}/classes/internal/api.yaml</specPath>
                            <generateClient>true</generateClient>
                            <basePackage>com.oracle.pic.identity.authentication</basePackage>
                            <specGenerationType>INTERNAL</specGenerationType>
                            <language>oracle-java-sdk</language>
                            <externalModels>
                                <DelegationTokenExchangeRequest>com.oracle.pic.identity.authentication.requests.ExchangeDtWithMatchingRuleRequest</DelegationTokenExchangeRequest>
                                <OnBehalfOfRequest>com.oracle.pic.identity.authentication.entities.OnBehalfOfRequest</OnBehalfOfRequest>
                                <SecurityToken>com.oracle.pic.identity.authentication.entities.SecurityToken</SecurityToken>
                                <X509FederationRequest>com.oracle.pic.identity.authentication.entities.X509FederationRequest</X509FederationRequest>
                                <DelegationTokenExchangeRequest>com.oracle.pic.identity.authentication.entities.DelegationTokenExchangeRequest</DelegationTokenExchangeRequest>
                                <ServicePrincipalSessionTokenRequest>com.oracle.pic.identity.authentication.entities.ServicePrincipalSessionTokenRequest</ServicePrincipalSessionTokenRequest>
                                <OauthExchangeTokenRequest>com.oracle.pic.identity.authentication.entities.OauthTokenRequest</OauthExchangeTokenRequest>>
                                <Principal>com.oracle.pic.identity.authentication.Principal</Principal>
                                <AuthenticationRequest>com.oracle.pic.identity.authentication.credential.AuthenticationRequest</AuthenticationRequest>>
                            </externalModels>
                            <additionalProperties>
                                 <loggerName>LOG</loggerName>
                            </additionalProperties>
                        </configuration>
                    </execution>
                </executions>
            </plugin>
        </plugins>
    </build>
</project>
