<?xml version="1.0" encoding="UTF-8"?>
<!--
    Copyright (c) 2025 Oracle and/or its affiliates.
-->
<project xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"
        xmlns="http://maven.apache.org/POM/4.0.0"
        xsi:schemaLocation="http://maven.apache.org/POM/4.0.0 https://maven.apache.org/xsd/maven-4.0.0.xsd">
    <modelVersion>4.0.0</modelVersion>
    <parent>
        <groupId>com.oracle.helidon.oci</groupId>
        <artifactId>helidon-repackaged-oci</artifactId>
        <version>1.2.1-SNAPSHOT</version>
        <relativePath>../pom.xml</relativePath>
    </parent>
    <artifactId>helidon-repackaged-oci-kiev-library</artifactId>
    <version>1.2.1-SNAPSHOT</version>
    <packaging>jar</packaging>

    <name>Helidon OCI Repackaged OCI kiev-library</name>

    <properties>
        <spotbugs.skip>true</spotbugs.skip>
        <codegen.base.package.name>com.oracle.pic.kiev.api</codegen.base.package.name>
        <frontend-spec-dir>${project.build.directory}/frontend/</frontend-spec-dir>
        <frontend-spec-file>${frontend-spec-dir}/frontend-spec.yaml</frontend-spec-file>
        <client-registry-spec-dir>${project.build.directory}/client-registry/</client-registry-spec-dir>
        <client-registry-spec-file>${client-registry-spec-dir}/client-registry-spec.yaml</client-registry-spec-file>
    </properties>

    <dependencies>
        <!-- https://oci.private.devops.scmservice.us-phoenix-1.oci.oracleiaas.com/namespaces/axuxirvibvvo/projects/KIEV/repositories/kiev-client -->
        <dependency>
            <groupId>com.oracle.pic.kiev</groupId>
            <artifactId>client-registry</artifactId>
            <version>${oracle-internal-kiev-library-version}</version>
            <scope>provided</scope>
            <exclusions>
                <exclusion>
                    <groupId>*</groupId>
                    <artifactId>*</artifactId>
                </exclusion>
            </exclusions>
        </dependency>
        <dependency>
            <groupId>com.oracle.pic.kiev</groupId>
            <artifactId>kiev-core</artifactId>
            <version>${oracle-internal-kiev-library-version}</version>
            <scope>provided</scope>
            <exclusions>
                <exclusion>
                    <groupId>*</groupId>
                    <artifactId>*</artifactId>
                </exclusion>
            </exclusions>
        </dependency>
        <dependency>
            <groupId>com.oracle.pic.kiev</groupId>
            <artifactId>kiev-db-common</artifactId>
            <version>${oracle-internal-kiev-library-version}</version>
            <scope>provided</scope>
            <exclusions>
                <exclusion>
                    <groupId>*</groupId>
                    <artifactId>*</artifactId>
                </exclusion>
            </exclusions>
        </dependency>
        <dependency>
            <groupId>com.oracle.pic.kiev</groupId>
            <artifactId>kiev-library</artifactId>
            <version>${oracle-internal-kiev-library-version}</version>
            <scope>provided</scope>
            <exclusions>
                <exclusion>
                    <groupId>*</groupId>
                    <artifactId>*</artifactId>
                </exclusion>
            </exclusions>
        </dependency>
        <dependency>
            <groupId>com.oracle.pic.kiev</groupId>
            <artifactId>service-client</artifactId>
            <version>${oracle-internal-kiev-library-version}</version>
            <scope>provided</scope>
            <exclusions>
                <exclusion>
                    <groupId>*</groupId>
                    <artifactId>*</artifactId>
                </exclusion>
            </exclusions>
        </dependency>
        <dependency>
            <groupId>com.oracle.pic.kiev</groupId>
            <artifactId>shared-models</artifactId>
            <version>${oracle-internal-kiev-library-version}</version>
            <scope>provided</scope>
            <exclusions>
                <exclusion>
                    <groupId>*</groupId>
                    <artifactId>*</artifactId>
                </exclusion>
            </exclusions>
        </dependency>
        <dependency>
            <groupId>com.oracle.oci.sdk</groupId>
            <artifactId>oci-java-sdk-common</artifactId>
            <exclusions>
                <exclusion>
                    <artifactId>javax.annotation-api</artifactId>
                    <groupId>javax.annotation</groupId>
                </exclusion>
                <exclusion>
                    <artifactId>hk2-locator</artifactId>
                    <groupId>org.glassfish.hk2</groupId>
                </exclusion>
                <exclusion>
                    <artifactId>jersey-common</artifactId>
                    <groupId>org.glassfish.jersey.core</groupId>
                </exclusion>
                <exclusion>
                    <artifactId>javax.ws.rs-api</artifactId>
                    <groupId>javax.ws.rs</groupId>
                </exclusion>
                <exclusion>
                    <artifactId>*</artifactId>
                    <groupId>org.bouncycastle</groupId>
                </exclusion>
                <exclusion>
                    <groupId>jakarta.xml.bind</groupId>
                    <artifactId>jakarta.xml.bind-api</artifactId>
                </exclusion>
                <exclusion>
                    <groupId>jakarta.activation</groupId>
                    <artifactId>jakarta.activation-api</artifactId>
                </exclusion>
                <exclusion>
                    <groupId>org.glassfish.jersey.connectors</groupId>
                    <artifactId>jersey-apache-connector</artifactId>
                </exclusion>
                <exclusion>
                    <groupId>jakarta.xml.bind</groupId>
                    <artifactId>jakarta.xml.bind-api</artifactId>
                </exclusion>
                <exclusion>
                    <groupId>jakarta.activation</groupId>
                    <artifactId>jakarta.activation-api</artifactId>
                </exclusion>
                <exclusion>
                    <groupId>org.glassfish.jersey.core</groupId>
                    <artifactId>jersey-client</artifactId>
                </exclusion>
            </exclusions>
        </dependency>
        <dependency>
            <groupId>com.oracle.oci.sdk</groupId>
            <artifactId>oci-java-sdk-circuitbreaker</artifactId>
        </dependency>
        <dependency>
            <groupId>jakarta.annotation</groupId>
            <artifactId>jakarta.annotation-api</artifactId>
        </dependency>
        <dependency>
            <groupId>com.fasterxml.jackson.core</groupId>
            <artifactId>jackson-annotations</artifactId>
        </dependency>
        <dependency>
            <groupId>com.fasterxml.jackson.core</groupId>
            <artifactId>jackson-databind</artifactId>
        </dependency>
        <dependency>
            <groupId>javax.ws.rs</groupId>
            <artifactId>javax.ws.rs-api</artifactId>
        </dependency>
        <dependency>
            <groupId>com.oracle.helidon.oci</groupId>
            <artifactId>helidon-oci-javax-shim</artifactId>
            <exclusions>
                <exclusion>
                    <groupId>com.oracle.oci.sdk</groupId>
                    <artifactId>oci-java-sdk-common-httpclient</artifactId>
                </exclusion>
            </exclusions>
        </dependency>
        <!-- Below from here is required at runtime, by user of this repackaged client. -->
        <dependency>
            <groupId>com.google.guava</groupId>
            <artifactId>guava</artifactId>
            <exclusions>
                <exclusion>
                    <groupId>com.google.errorprone</groupId>
                    <artifactId>error_prone_annotations</artifactId>
                </exclusion>
            </exclusions>
        </dependency>
        <dependency>
            <groupId>org.apache.commons</groupId>
            <artifactId>commons-lang3</artifactId>
        </dependency>
        <dependency>
            <groupId>com.oracle.pic.commons</groupId>
            <artifactId>metrics</artifactId>
            <exclusions>
                <exclusion>
                    <groupId>com.oracle.pic.telemetry.commons</groupId>
                    <artifactId>metrics-reporter</artifactId>
                </exclusion>
                <exclusion>
                    <artifactId>assertj-core</artifactId>
                    <groupId>org.assertj</groupId>
                </exclusion>
                <exclusion>
                    <artifactId>guice</artifactId>
                    <groupId>com.google.inject</groupId>
                </exclusion>
                <exclusion>
                    <artifactId>javax.ws.rs-api</artifactId>
                    <groupId>javax.ws.rs</groupId>
                </exclusion>
                <exclusion>
                    <groupId>org.glassfish.jersey.core</groupId>
                    <artifactId>jersey-client</artifactId>
                </exclusion>
                <exclusion>
                    <groupId>org.apache.commons</groupId>
                    <artifactId>commons-lang</artifactId>
                </exclusion>
            </exclusions>
        </dependency>
    </dependencies>
    <build>
        <pluginManagement>
            <plugins>
                <plugin>
                    <groupId>org.apache.maven.plugins</groupId>
                    <artifactId>maven-dependency-plugin</artifactId>
                    <configuration>
                        <ignoredUnusedDeclaredDependencies>
                            <ignoredUnusedDeclaredDependency>com.oracle.pic.kiev:*-spec</ignoredUnusedDeclaredDependency>
                        </ignoredUnusedDeclaredDependencies>
                    </configuration>
                </plugin>
            </plugins>
        </pluginManagement>
        <plugins>
            <plugin>
                <!-- Unpack service model specifications. -->
                <groupId>org.apache.maven.plugins</groupId>
                <artifactId>maven-dependency-plugin</artifactId>
                <executions>
                    <execution>
                        <id>unpack-kiev-frontend-spec</id>
                        <phase>initialize</phase>
                        <goals>
                            <goal>unpack</goal>
                        </goals>
                        <configuration>
                            <artifactItems>
                                <artifactItem>
                                    <groupId>com.oracle.pic.kiev</groupId>
                                    <artifactId>frontend-spec</artifactId>
                                    <version>${oracle-internal-kiev-spec-version}</version>
                                    <type>jar</type>
                                    <includes>frontend-spec.yaml</includes>
                                    <outputDirectory>${frontend-spec-dir}</outputDirectory>
                                </artifactItem>
                            </artifactItems>
                        </configuration>
                    </execution>
                    <execution>
                        <id>unpack-kiev-client-registry-spec</id>
                        <phase>initialize</phase>
                        <goals>
                            <goal>unpack</goal>
                        </goals>
                        <configuration>
                            <artifactItems>
                                <artifactItem>
                                    <groupId>com.oracle.pic.kiev</groupId>
                                    <artifactId>client-registry-spec</artifactId>
                                    <version>${oracle-internal-kiev-spec-version}</version>
                                    <type>jar</type>
                                    <includes>client-registry-spec.yaml</includes>
                                    <outputDirectory>${client-registry-spec-dir}</outputDirectory>
                                </artifactItem>
                            </artifactItems>
                        </configuration>
                    </execution>
                </executions>
            </plugin>
            <plugin>
                <groupId>org.codehaus.mojo</groupId>
                <artifactId>build-helper-maven-plugin</artifactId>
                <executions>
                    <execution>
                        <phase>generate-sources</phase>
                        <goals>
                            <goal>add-source</goal>
                        </goals>
                        <configuration>
                            <sources>
                                <source>
                                    ${project.build.directory}/generated-sources/${codegen.base.package.name}/oracle-java-sdk-sources
                                </source>
                            </sources>
                        </configuration>
                    </execution>
                </executions>
            </plugin>
            <plugin>
                <groupId>com.oracle.helidon.oci</groupId>
                <artifactId>helidon-oci-repackage-plugin</artifactId>
                <version>1.2.1-SNAPSHOT</version>
                <executions>
                    <execution>
                        <goals>
                            <goal>repackage-oci-libs</goal>
                        </goals>
                    </execution>
                </executions>
                <configuration>
                    <artifacts>
                        <artifact>
                            <groupId>com.oracle.pic.kiev</groupId>
                            <artifactId>client-registry</artifactId>
                        </artifact>
                        <artifact>
                            <groupId>com.oracle.pic.kiev</groupId>
                            <artifactId>kiev-core</artifactId>
                        </artifact>
                        <artifact>
                            <groupId>com.oracle.pic.kiev</groupId>
                            <artifactId>kiev-db-common</artifactId>
                        </artifact>
                        <artifact>
                            <groupId>com.oracle.pic.kiev</groupId>
                            <artifactId>kiev-library</artifactId>
                        </artifact>
                        <artifact>
                            <groupId>com.oracle.pic.kiev</groupId>
                            <artifactId>service-client</artifactId>
                        </artifact>
                        <artifact>
                            <groupId>com.oracle.pic.kiev</groupId>
                            <artifactId>shared-models</artifactId>
                            <exclusions>
                                <exclusion>com/oracle/pic/kiev/api/[^/]*\.class</exclusion>
                            </exclusions>
                        </artifact>
                    </artifacts>
                </configuration>
            </plugin>
            <plugin>
                <groupId>com.oracle.bmc.sdk</groupId>
                <artifactId>bmc-sdk-swagger-maven-plugin</artifactId>
                <version>2.135-3.72.0</version>
                <executions>
                    <execution>
                        <id>generate-frontend-s2s-client</id>
                        <phase>generate-sources</phase>
                        <goals>
                            <goal>generate</goal>
                        </goals>
                        <configuration>
                            <language>oracle-java-sdk</language>
                            <basePackage>${codegen.base.package.name}</basePackage>
                            <specPath>${frontend-spec-file}</specPath>
                            <additionalProperties>
                                <!-- Switch the default client configurator to NonBuffering as is relevant to streaming large payloads -->
                                <defaultClientConfigurator>com.oracle.bmc.http.DefaultConfigurator.NonBuffering
                                </defaultClientConfigurator>
                                <generateWaiters>false</generateWaiters>
                                <generatePaginators>false</generatePaginators>
                                <useExplicitlySetFilter>false</useExplicitlySetFilter>
                            </additionalProperties>
                            <outputDir>${project.build.directory}/generated-sources/${codegen.base.package.name}</outputDir>
                            <specGenerationType>INTERNAL</specGenerationType>
                            <isTestGenerationEnabled>false</isTestGenerationEnabled>
                            <isExpect100ContinueSupported>false</isExpect100ContinueSupported>
                        </configuration>
                    </execution>
                    <execution>
                        <id>generate-client-registry-s2s-client</id>
                        <phase>generate-sources</phase>
                        <goals>
                            <goal>generate</goal>
                        </goals>
                        <configuration>
                            <language>oracle-java-sdk</language>
                            <basePackage>${codegen.base.package.name}</basePackage>
                            <specPath>${client-registry-spec-file}</specPath>
                            <additionalProperties>
                                <generateWaiters>false</generateWaiters>
                                <generatePaginators>false</generatePaginators>
                                <useExplicitlySetFilter>false</useExplicitlySetFilter>
                            </additionalProperties>
                            <outputDir>${project.build.directory}/generated-sources/${codegen.base.package.name}</outputDir>
                            <specGenerationType>INTERNAL</specGenerationType>
                            <isTestGenerationEnabled>false</isTestGenerationEnabled>
                            <isExpect100ContinueSupported>false</isExpect100ContinueSupported>
                        </configuration>
                    </execution>
                </executions>
            </plugin>
        </plugins>
    </build>
</project>