#
# Copyright (c) 2026 Oracle and/or its affiliates.
#

server:
  port: 8080
  host: 0.0.0.0

declarative:
  ignore-incubating: true

oci:
  kiev:
    data-stores:
      - backend: "IN_MEMORY"
        store-name: helidon-store-example
        app-name: helidon-store-example
        transaction-max-reads: 100
        transaction-max-writes: 100

# To switch to Kiev as a service with a shared OCI SDK auth provider:
# helidon:
#   oci:
#     authentication-method: instance-principal
#
# oci:
#   kiev:
#     data-stores:
#       - backend: "SERVICE"
#         store-name: helidon-store-example
#         app-name: helidon-store-example
#         service:
#           compartment-id: ocid1.compartment.oc1...
#           frontend-endpoint: https://your-kiev-endpoint
#           locality: "REGIONAL"
#           auth:
#             type: "OVERRIDDEN"
#             tls:
#               root-cert-pem-path: /etc/oci-pki/ca-bundle.pem
#               cert-reload-duration: PT5M
#               cert-ssl-algorithm: SunX509
#         stream-deleted-column-values: true
#
# For Kiev as a service with S2S auth:
# oci:
#   kiev:
#     data-stores:
#       - backend: "SERVICE"
#         store-name: helidon-store-example
#         app-name: helidon-store-example
#         service:
#           compartment-id: ocid1.compartment.oc1...
#           frontend-endpoint: https://your-kiev-endpoint
#           locality: "AD1"
#           auth:
#             type: "S2S"
#             tls:
#               root-cert-pem-path: /etc/oci-pki/ca-bundle.pem
#               cert-reload-duration: PT15M
#               cert-ssl-algorithm: SunX509
#             service-principal:
#               federation-endpoint: https://auth.example
#               tenant-id: ocid1.tenancy.oc1...
#               certificates:
#                 - certificate: /path/to/leaf.pem
#                   private-key: /path/to/leaf.key
#                   passphrase: secret
#                 - certificate: /path/to/intermediate.pem
#         stream-deleted-column-values: true
#
# For local KIAB KaaS, use:
# oci:
#   kiev:
#     data-stores:
#       - backend: "SERVICE"
#         store-name: helidon-store-example
#         app-name: helidon-store-example
#         service:
#           compartment-id: ocid1.compartment.dev..aaaaaaaawbxxkux3w7df6qki32ejszm75vsxsnztljeerhzrw3vsa7d3rjmq
#           frontend-endpoint: http://localhost:16666
#           locality: "REGIONAL"
#           auth:
#             type: "KIAB_LOCAL"
#         stream-deleted-column-values: true
