<?xml version="1.0" encoding="UTF-8"?>
<!--
    Copyright (c) 2026 Oracle and/or its affiliates.
-->

<project xmlns="http://maven.apache.org/POM/4.0.0"
        xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"
        xsi:schemaLocation="http://maven.apache.org/POM/4.0.0
                             https://maven.apache.org/xsd/maven-4.0.0.xsd">
    <modelVersion>4.0.0</modelVersion>
    <!-- Parent pom defines some properties (like helidon.oci.version) and configures plugins -->
    <parent>
        <groupId>com.oracle.helidon.oci</groupId>
        <artifactId>helidon-oci-se</artifactId>
        <version>2.0.0-SNAPSHOT</version>
        <relativePath>../../applications/se</relativePath>
    </parent>

    <groupId>com.oracle.helidon.oci.examples.dataplane</groupId>
    <artifactId>helidon-oci-examples-dataplane</artifactId>
    <version>1.0.0-SNAPSHOT</version>
    <name>Helidon Talon Examples Data Plane</name>

    <properties>
        <mainClass>com.oracle.helidon.oci.examples.dataplane.Main</mainClass>
    </properties>

    <dependencyManagement>
        <dependencies>
            <!-- The order of these imports is important. First has precedence over later. -->
            <!-- Manage versions of com.oracle.pic artifacts -->
            <dependency>
                <groupId>com.oracle.helidon.oci</groupId>
                <artifactId>helidon-oci-internal-bom</artifactId>
                <version>${helidon.oci.version}</version>
                <type>pom</type>
                <scope>import</scope>
            </dependency>
            <!-- Manage versions of io.helidon, com.oracle.helidon and associated third party artifacts -->
            <dependency>
                <groupId>com.oracle.helidon.oci</groupId>
                <artifactId>helidon-oci-dependencies</artifactId>
                <version>${helidon.oci.version}</version>
                <type>pom</type>
                <scope>import</scope>
            </dependency>
            <!-- Manage versions of additional OCI third party artifacts -->
            <dependency>
                <groupId>com.oracle.pic.commons</groupId>
                <artifactId>dropwizard-service-bom</artifactId>
                <version>${version.oci.dropwizard.bom}</version>
                <type>pom</type>
                <scope>import</scope>
            </dependency>
        </dependencies>
    </dependencyManagement>

    <dependencies>
        <dependency>
            <groupId>io.helidon.config</groupId>
            <artifactId>helidon-config-yaml</artifactId>
        </dependency>
        <dependency>
            <groupId>io.helidon.http.media</groupId>
            <artifactId>helidon-http-media-json-binding</artifactId>
        </dependency>
        <dependency>
            <groupId>io.helidon.json</groupId>
            <artifactId>helidon-json-binding</artifactId>
        </dependency>
        <dependency>
            <groupId>io.helidon.logging</groupId>
            <artifactId>helidon-logging-jul</artifactId>
            <scope>runtime</scope>
        </dependency>
        <dependency>
            <groupId>io.helidon.service</groupId>
            <artifactId>helidon-service-registry</artifactId>
        </dependency>
        <dependency>
            <groupId>io.helidon.webserver</groupId>
            <artifactId>helidon-webserver</artifactId>
        </dependency>
        <dependency>
            <groupId>com.oracle.helidon.oci</groupId>
            <artifactId>helidon-oci-audit</artifactId>
        </dependency>
        <dependency>
            <groupId>com.oracle.helidon.oci.kiev</groupId>
            <artifactId>helidon-oci-kiev</artifactId>
        </dependency>
        <dependency>
            <groupId>com.oracle.helidon.oci.envconfig</groupId>
            <artifactId>helidon-oci-envconfig</artifactId>
            <scope>runtime</scope>
        </dependency>
        <dependency>
            <groupId>com.oracle.helidon.oci.errorcode</groupId>
            <artifactId>helidon-oci-errorcode</artifactId>
        </dependency>
        <dependency>
            <groupId>com.oracle.helidon.oci.errorcode</groupId>
            <artifactId>helidon-oci-errorcode-webserver</artifactId>
            <scope>runtime</scope>
        </dependency>
        <dependency>
            <groupId>com.oracle.helidon.oci.identity</groupId>
            <artifactId>helidon-oci-identity</artifactId>
        </dependency>
        <dependency>
            <groupId>com.oracle.helidon.oci.jaxrs</groupId>
            <artifactId>helidon-oci-jaxrs</artifactId>
        </dependency>
        <dependency>
            <groupId>com.oracle.helidon.oci.metrics</groupId>
            <artifactId>helidon-oci-metrics</artifactId>
            <scope>runtime</scope>
        </dependency>
        <dependency>
            <groupId>com.oracle.helidon.oci.requestid</groupId>
            <artifactId>helidon-oci-request-id-webserver</artifactId>
        </dependency>
        <dependency>
            <groupId>com.oracle.helidon.oci.secret-service</groupId>
            <artifactId>helidon-oci-secret-service-tls-manager</artifactId>
            <scope>runtime</scope>
        </dependency>
        <dependency>
            <groupId>org.slf4j</groupId>
            <artifactId>slf4j-api</artifactId>
        </dependency>
        <dependency>
            <groupId>ch.qos.logback</groupId>
            <artifactId>logback-core</artifactId>
            <scope>runtime</scope>
        </dependency>
        <dependency>
            <groupId>io.helidon.webclient</groupId>
            <artifactId>helidon-webclient-http1</artifactId>
            <scope>test</scope>
        </dependency>
        <dependency>
            <groupId>io.helidon.webserver.testing.junit5</groupId>
            <artifactId>helidon-webserver-testing-junit5</artifactId>
            <scope>test</scope>
        </dependency>
        <dependency>
            <groupId>org.junit.jupiter</groupId>
            <artifactId>junit-jupiter-api</artifactId>
            <scope>test</scope>
        </dependency>
        <dependency>
            <groupId>org.hamcrest</groupId>
            <artifactId>hamcrest-all</artifactId>
            <scope>test</scope>
        </dependency>
    </dependencies>

    <build>
        <plugins>
            <plugin>
                <groupId>org.apache.maven.plugins</groupId>
                <artifactId>maven-surefire-plugin</artifactId>
                <configuration>
                    <forkCount>1</forkCount>
                    <reuseForks>false</reuseForks>
                    <childDelegation>true</childDelegation>
                    <useSystemClassLoader>false</useSystemClassLoader>
                    <runOrder>alphabetical</runOrder>
                    <systemPropertyVariables>
                        <helidon.config.profile>test</helidon.config.profile>
                    </systemPropertyVariables>
                </configuration>
            </plugin>
            <plugin>
                <groupId>org.apache.maven.plugins</groupId>
                <artifactId>maven-dependency-plugin</artifactId>
                <executions>
                    <execution>
                        <id>copy-libs</id>
                    </execution>
                </executions>
            </plugin>
            <plugin>
                <groupId>org.apache.maven.plugins</groupId>
                <artifactId>maven-compiler-plugin</artifactId>
                <configuration>
                    <annotationProcessorPaths>
                        <path>
                            <groupId>io.helidon.bundles</groupId>
                            <artifactId>helidon-bundles-apt</artifactId>
                            <version>${helidon.version}</version>
                        </path>
                        <path>
                            <groupId>com.oracle.helidon.oci</groupId>
                            <artifactId>helidon-oci-codegen</artifactId>
                            <version>${helidon.oci.version}</version>
                        </path>
                    </annotationProcessorPaths>
                </configuration>
            </plugin>
            <plugin>
                <groupId>io.helidon.service</groupId>
                <artifactId>helidon-service-maven-plugin</artifactId>
                <version>${helidon.version}</version>
                <executions>
                    <execution>
                        <id>create-application</id>
                        <goals>
                            <goal>create-application</goal>
                        </goals>
                    </execution>
                </executions>
            </plugin>
        </plugins>
    </build>
</project>
