<?xml version="1.0" encoding="UTF-8"?>
<!--
    Copyright (c) 2025 Oracle and/or its affiliates.
-->
<project xmlns="http://maven.apache.org/POM/4.0.0"
        xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"
        xsi:schemaLocation="http://maven.apache.org/POM/4.0.0 https://maven.apache.org/xsd/maven-4.0.0.xsd">
    <modelVersion>4.0.0</modelVersion>
    <parent>
        <groupId>com.oracle.helidon.oci</groupId>
        <artifactId>helidon-repackaged-oci</artifactId>
        <version>1.2.1-SNAPSHOT</version>
        <relativePath>../pom.xml</relativePath>
    </parent>
    <artifactId>helidon-repackaged-oci-workflow-javaclient</artifactId>
    <version>1.2.1-SNAPSHOT</version>
    <packaging>jar</packaging>
    <name>Helidon OCI Repackaged OCI Workflow Java Client</name>

    <properties>
        <spotbugs.exclude>etc/spotbugs/exclude.xml</spotbugs.exclude>
    </properties>

    <dependencies>
        <dependency>
            <groupId>com.oracle.pic.workflow</groupId>
            <artifactId>workflow-javaclient</artifactId>
            <scope>provided</scope>
        </dependency>
        <dependency>
            <groupId>com.oracle.helidon.oci</groupId>
            <artifactId>helidon-repackaged-oci-workflow-service-java-client</artifactId>
        </dependency>
        <dependency>
            <groupId>jakarta.enterprise</groupId>
            <artifactId>jakarta.enterprise.cdi-api</artifactId>
        </dependency>
        <dependency>
            <groupId>com.oracle.pic.commons</groupId>
            <artifactId>core</artifactId>
        </dependency>
        <dependency>
            <groupId>com.oracle.oci.sdk</groupId>
            <artifactId>oci-java-sdk-common</artifactId>
        </dependency>
        <dependency>
            <groupId>com.oracle.pic.commons</groupId>
            <artifactId>s2s-client-util</artifactId>
            <version>1.0.7</version>
            <exclusions>
                <exclusion>
                    <groupId>com.google.code.findbugs</groupId>
                    <artifactId>annotations</artifactId>
                </exclusion>
            </exclusions>
        </dependency>
    </dependencies>

    <build>
        <plugins>
            <plugin>
                <groupId>com.oracle.helidon.oci</groupId>
                <artifactId>helidon-oci-repackage-plugin</artifactId>
                <executions>
                    <execution>
                        <goals>
                            <goal>repackage-oci-libs</goal>
                        </goals>
                    </execution>
                </executions>
                <configuration>
                    <artifacts>
                        <artifact>
                            <groupId>com.oracle.pic.workflow</groupId>
                            <artifactId>workflow-javaclient</artifactId>
                            <exclusions>
                                <exclusion>com/oracle/pic/workflow/module/WorkflowClientModule.class</exclusion>
                                <!-- This is sample directory only, so no need to be included as it has no functional value -->
                                <exclusion>com/oracle/pic/workflow/sample/[^/]*\.class</exclusion>
                            </exclusions>
                        </artifact>
                    </artifacts>
                </configuration>
            </plugin>
        </plugins>
    </build>
</project>
