<?xml version="1.0" encoding="UTF-8"?>
<!--
    Copyright (c) 2024, 2025 Oracle and/or its affiliates.
-->

<project xmlns="http://maven.apache.org/POM/4.0.0"
        xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"
        xsi:schemaLocation="http://maven.apache.org/POM/4.0.0 http://maven.apache.org/xsd/maven-4.0.0.xsd">
    <parent>
        <groupId>com.oracle.helidon.oci</groupId>
        <artifactId>helidon-oci-project</artifactId>
        <version>1.2.1-SNAPSHOT</version>
        <relativePath>../pom.xml</relativePath>
    </parent>
    <modelVersion>4.0.0</modelVersion>

    <artifactId>helidon-repackaged-oci</artifactId>
    <name>Helidon OCI Repackaged Native Modules</name>
    <packaging>pom</packaging>

    <modules>
        <module>javax-shim</module>
        <module>javax-jersey-shim</module>
        <module>repackage-plugin</module>
        <module>repackaged-oci-splat-sdk</module>
        <module>repackaged-oci-authentication-client</module>
        <module>repackaged-oci-authorization-sdk</module>
        <module>repackaged-oci-vault-java-sdk</module>
    </modules>


    <build>
        <pluginManagement>
            <plugins>
                <plugin>
                    <groupId>org.apache.maven.plugins</groupId>
                    <artifactId>maven-dependency-plugin</artifactId>
                    <executions>
                        <execution>
                            <id>get-spec-from-artifactory</id>
                            <phase>initialize</phase>
                            <goals>
                                <goal>unpack</goal>
                            </goals>
                            <configuration>
                                <artifactItems>
                                    <artifactItem>
                                        <groupId>${codegen.artifactory.groupId}</groupId>
                                        <artifactId>${codegen.artifactory.artifactId}</artifactId>
                                        <version>${codegen.artifactory.version}</version>
                                        <type>jar</type>
                                        <includes>${codegen.spec.name}</includes>
                                        <outputDirectory>${codegen.spec.dir}</outputDirectory>
                                    </artifactItem>
                                </artifactItems>
                            </configuration>
                        </execution>
                    </executions>
                </plugin>
                <plugin>
                    <groupId>org.codehaus.mojo</groupId>
                    <artifactId>build-helper-maven-plugin</artifactId>
                    <executions>
                        <execution>
                            <id>add-source-root</id>
                            <phase>generate-sources</phase>
                            <goals>
                                <goal>add-source</goal>
                            </goals>
                            <configuration>
                                <sources>
                                    <source>${project.build.directory}/generated-sources/${codegen.base.package.name}/oracle-java-sdk-sources</source>
                                </sources>
                            </configuration>
                        </execution>
                    </executions>
                </plugin>
                <plugin>
                    <groupId>org.projectlombok</groupId>
                    <artifactId>lombok-maven-plugin</artifactId>
                    <executions>
                        <execution>
                            <id>delombok</id>
                            <phase>process-sources</phase>
                            <goals>
                                <goal>delombok</goal>
                            </goals>
                            <configuration>
                                <addOutputDirectory>false</addOutputDirectory>
                                <!-- Only delombok for docs -->
                                <outputDirectory>target/generated-sources-for-docs/delombok</outputDirectory>
                                <sourceDirectory>${project.build.directory}/generated-sources/${codegen.base.package.name}/oracle-java-sdk-sources</sourceDirectory>
                                <encoding>UTF-8</encoding>
                                <formatPreferences>
                                    <javaLangAsFQN>skip</javaLangAsFQN>
                                    <generateDelombokComment>skip</generateDelombokComment>
                                    <generated>skip</generated>
                                    <indent>4</indent>
                                    <suppressWarnings>skip</suppressWarnings>
                                </formatPreferences>
                                <verbose>true</verbose>
                            </configuration>
                        </execution>
                    </executions>
                </plugin>
                <plugin>
                    <groupId>org.apache.maven.plugins</groupId>
                    <artifactId>maven-javadoc-plugin</artifactId>
                    <goals>
                        <goal>jar</goal>
                    </goals>
                    <executions>
                        <execution>
                            <id>aggregate</id>
                            <phase>package</phase>
                            <goals>
                                <goal>jar</goal>
                            </goals>
                        </execution>
                    </executions>
                    <configuration>
                        <doclet>ch.raffael.doclets.pegdown.PegdownDoclet</doclet>
                        <docletArtifact>
                            <groupId>ch.raffael.pegdown-doclet</groupId>
                            <artifactId>pegdown-doclet</artifactId>
                            <version>1.3</version>
                        </docletArtifact>
                        <useStandardDocletOptions>true</useStandardDocletOptions>
                        <aggregate>true</aggregate>
                        <minmemory>128m</minmemory>
                        <maxmemory>1024m</maxmemory>
                        <additionalparam>-Xdoclint:none -disable-highlight</additionalparam>
                        <sourcepath>target/generated-sources-for-docs/delombok</sourcepath>
                        <links>
                            <link>https://jax-rs-spec.java.net/nonav/2.0-rev-a/apidocs</link>
                            <link>https://docs.cloud.oracle.com/iaas/tools/java/latest</link>
                        </links>
                    </configuration>
                </plugin>
            </plugins>
        </pluginManagement>
    </build>
</project>