<?xml version="1.0" encoding="UTF-8"?>
<!--
    Copyright (c) 2025 Oracle and/or its affiliates.
-->
<project xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"
        xmlns="http://maven.apache.org/POM/4.0.0"
        xsi:schemaLocation="http://maven.apache.org/POM/4.0.0 https://maven.apache.org/xsd/maven-4.0.0.xsd">
    <modelVersion>4.0.0</modelVersion>
    <parent>
        <groupId>com.oracle.helidon.oci</groupId>
        <artifactId>helidon-repackaged-oci</artifactId>
        <version>1.2.1-SNAPSHOT</version>
        <relativePath>../pom.xml</relativePath>
    </parent>
    <artifactId>helidon-repackaged-oci-kiev-in-memory-library</artifactId>
    <version>1.2.1-SNAPSHOT</version>
    <packaging>jar</packaging>

    <name>Helidon OCI Repackaged OCI kiev-in-memory-library</name>

    <properties>
        <spotbugs.skip>true</spotbugs.skip>
    </properties>

    <dependencies>
        <!-- https://oci.private.devops.scmservice.us-phoenix-1.oci.oracleiaas.com/namespaces/axuxirvibvvo/projects/KIEV/repositories/kiev-client -->
        <dependency>
            <groupId>com.oracle.pic.kiev</groupId>
            <artifactId>in-memory-core</artifactId>
            <version>${oracle-internal-kiev-library-version}</version>
            <scope>provided</scope>
            <exclusions>
                <exclusion>
                    <groupId>*</groupId>
                    <artifactId>*</artifactId>
                </exclusion>
            </exclusions>
        </dependency>
        <dependency>
            <groupId>com.oracle.pic.kiev</groupId>
            <artifactId>in-memory-library</artifactId>
            <version>${oracle-internal-kiev-library-version}</version>
            <scope>provided</scope>
            <exclusions>
                <exclusion>
                    <groupId>*</groupId>
                    <artifactId>*</artifactId>
                </exclusion>
            </exclusions>
        </dependency>
    </dependencies>

    <build>
        <plugins>
            <plugin>
                <groupId>com.oracle.helidon.oci</groupId>
                <artifactId>helidon-oci-repackage-plugin</artifactId>
                <version>1.2.1-SNAPSHOT</version>
                <executions>
                    <execution>
                        <goals>
                            <goal>repackage-oci-libs</goal>
                        </goals>
                    </execution>
                </executions>
                <configuration>
                    <artifacts>
                        <artifact>
                            <groupId>com.oracle.pic.kiev</groupId>
                            <artifactId>in-memory-core</artifactId>
                        </artifact>
                        <artifact>
                            <groupId>com.oracle.pic.kiev</groupId>
                            <artifactId>in-memory-library</artifactId>
                        </artifact>
                    </artifacts>
                </configuration>
            </plugin>
        </plugins>
    </build>

</project>