/*
 * Copyright (c) 2023 Oracle and/or its affiliates.
 *
 * Licensed under the Apache License, Version 2.0 (the "License");
 * you may not use this file except in compliance with the License.
 * You may obtain a copy of the License at
 *
 *     http://www.apache.org/licenses/LICENSE-2.0
 *
 * Unless required by applicable law or agreed to in writing, software
 * distributed under the License is distributed on an "AS IS" BASIS,
 * WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
 * See the License for the specific language governing permissions and
 * limitations under the License.
 */

package com.oracle.helidon.oci.requestid;

import io.helidon.common.context.Contexts;
import com.oracle.helidon.oci.requestid.generator.OpcRequestIdGenerator;
import io.helidon.logging.common.HelidonMdc;

import jakarta.annotation.Priority;
import jakarta.ws.rs.Priorities;
import jakarta.ws.rs.container.ContainerRequestContext;
import jakarta.ws.rs.container.ContainerRequestFilter;
import jakarta.ws.rs.container.ContainerResponseContext;
import jakarta.ws.rs.container.ContainerResponseFilter;
import jakarta.ws.rs.container.PreMatching;
import jakarta.ws.rs.core.Request;

import static com.oracle.helidon.oci.requestid.OciHeaderNames.OPC_REQUEST_ID;

/**
 * Ensures all client requests include the opc-request-id header: which is either
 * received on the request or generated by this filter. Also makes the header value
 * available in the MDC context for logging, and to the Helidon context for general
 * processing of the request.
 */
@PreMatching
@Priority(Priorities.AUTHENTICATION - 100)
class RequestIdServerFilter implements ContainerRequestFilter, ContainerResponseFilter {

    @Override
    public void filter(ContainerRequestContext requestContext) {
        String requestId = OpcRequestIdGenerator.getOpcRequestId(requestContext.getHeaderString(OPC_REQUEST_ID));
        requestContext.getHeaders().add(OPC_REQUEST_ID, requestId);

        // register requestId in useful contexts
        HelidonMdc.set(OPC_REQUEST_ID, requestId);
        Contexts.context().ifPresent(c -> c.register(Request.class, requestId));
    }

    @Override
    public void filter(ContainerRequestContext requestContext, ContainerResponseContext responseContext) {
        String requestId = responseContext.getHeaderString(OPC_REQUEST_ID);
        if (requestId == null || requestId.isEmpty()) {
            responseContext.getHeaders().add(OPC_REQUEST_ID, requestContext.getHeaderString(OPC_REQUEST_ID));
        }
    }
}
