<?xml version="1.0" encoding="UTF-8"?>
<!--
    Copyright (c) 2026 Oracle and/or its affiliates.
-->

<project xmlns="http://maven.apache.org/POM/4.0.0"
        xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"
        xsi:schemaLocation="http://maven.apache.org/POM/4.0.0 http://maven.apache.org/xsd/maven-4.0.0.xsd">
    <modelVersion>4.0.0</modelVersion>
    <parent>
        <groupId>com.oracle.helidon.oci</groupId>
        <artifactId>helidon-oci-project</artifactId>
        <version>2.0.0-SNAPSHOT</version>
        <relativePath>../pom.xml</relativePath>
    </parent>

    <artifactId>helidon-oci-codegen</artifactId>
    <name>Helidon OCI Codegen</name>

    <dependencies>
        <dependency>
            <groupId>io.helidon.common</groupId>
            <artifactId>helidon-common</artifactId>
        </dependency>
        <dependency>
            <groupId>io.helidon.common</groupId>
            <artifactId>helidon-common-types</artifactId>
        </dependency>
        <dependency>
            <groupId>io.helidon.codegen</groupId>
            <artifactId>helidon-codegen</artifactId>
        </dependency>
        <dependency>
            <groupId>io.helidon.declarative</groupId>
            <artifactId>helidon-declarative-codegen-model</artifactId>
        </dependency>
        <dependency>
            <groupId>io.helidon.declarative</groupId>
            <artifactId>helidon-declarative-codegen</artifactId>
        </dependency>
        <dependency>
            <groupId>io.helidon.codegen</groupId>
            <artifactId>helidon-codegen-class-model</artifactId>
        </dependency>
        <dependency>
            <groupId>io.helidon.service</groupId>
            <artifactId>helidon-service-codegen</artifactId>
        </dependency>
        <dependency>
            <groupId>org.junit.jupiter</groupId>
            <artifactId>junit-jupiter-api</artifactId>
            <scope>test</scope>
        </dependency>
    </dependencies>

    <build>
        <plugins>
            <plugin>
                <groupId>io.helidon.build-tools</groupId>
                <artifactId>helidon-services-plugin</artifactId>
                <executions>
                    <execution>
                        <id>generate-meta-inf-services</id>
                        <phase>compile</phase>
                        <goals>
                            <goal>services</goal>
                        </goals>
                    </execution>
                </executions>
            </plugin>
        </plugins>
    </build>
</project>
