<?xml version="1.0" encoding="UTF-8"?>
<!--
    Copyright (c) 2023, 2026 Oracle and/or its affiliates.
-->

<project xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"
        xmlns="http://maven.apache.org/POM/4.0.0"
        xsi:schemaLocation="http://maven.apache.org/POM/4.0.0 https://maven.apache.org/xsd/maven-4.0.0.xsd">
    <parent>
        <groupId>com.oracle.helidon.oci.tests</groupId>
        <artifactId>helidon-oci-tests-project</artifactId>
        <version>2.0.0-SNAPSHOT</version>
        <relativePath>../pom.xml</relativePath>
    </parent>
    <modelVersion>4.0.0</modelVersion>

    <groupId>com.oracle.helidon.oci.tests.integration</groupId>
    <artifactId>helidon-oci-tests-integration</artifactId>
    <name>Helidon OCI Integration Tests</name>
    <packaging>pom</packaging>

    <modules>
        <module>authentication</module>
        <module>identity</module>
        <module>kiev</module>
        <module>secret-service</module>
    </modules>

    <build>
        <plugins>
            <plugin>
                <groupId>org.apache.maven.plugins</groupId>
                <artifactId>maven-failsafe-plugin</artifactId>
                <configuration>
                    <redirectTestOutputToFile>false</redirectTestOutputToFile>
                    <reuseForks>false</reuseForks>
                    <includes>
                        <include>**/*IT.java</include>
                    </includes>
                </configuration>
                <executions>
                    <execution>
                        <id>verify</id>
                        <phase>verify</phase>
                        <goals>
                            <goal>integration-test</goal>
                            <goal>verify</goal>
                        </goals>
                    </execution>
                </executions>
            </plugin>
        </plugins>
    </build>

    <profiles>
        <profile>
            <id>STTest</id>
            <build>
                <plugins>
                    <plugin>
                        <groupId>org.apache.maven.plugins</groupId>
                        <artifactId>maven-failsafe-plugin</artifactId>
                        <configuration>
                            <redirectTestOutputToFile>false</redirectTestOutputToFile>
                            <reuseForks>false</reuseForks>
                            <includes>
                                <include>**/*IT.java</include>
                            </includes>
                            <excludes>
                                <exclude>**/Ssv2EndpointIT.java</exclude>
                            </excludes>
                            <environmentVariables>
                                <HELIDON_OCI_IMDS_DASH_BASE_DASH_URI>http://localhost:8000/opc/v2/
                                </HELIDON_OCI_IMDS_DASH_BASE_DASH_URI>
                                <OCI_IDENTITY_AUTHENTICATION_INSTANCE_DASH_PRINCIPAL_DASH_URI>http://localhost:8000</OCI_IDENTITY_AUTHENTICATION_INSTANCE_DASH_PRINCIPAL_DASH_URI>
                                <OCI_METADATA_BASE_URL>http://localhost:8000/opc/v2/
                                </OCI_METADATA_BASE_URL>
                            </environmentVariables>
                        </configuration>
                        <executions>
                            <execution>
                                <id>verify</id>
                                <phase>verify</phase>
                                <goals>
                                    <goal>integration-test</goal>
                                    <goal>verify</goal>
                                </goals>
                            </execution>
                        </executions>
                    </plugin>
                </plugins>
            </build>
        </profile>
    </profiles>
</project>
