#
# Copyright (c) 2026 Oracle and/or its affiliates.
#

server:
  port: 8080
  host: 0.0.0.0
  features:
    request-scope:
      enabled: true

oci:
  identity:
    authentication:
      global-business-unit: my-business-unit
      team-name: my-team
      application-name: helidon-tagging-example
      instance-principal-uri: http://localhost:8000
      root-cert-path: /etc/oci-pki/ca-bundle.pem
      hard-coded-key-supplier: ${helidon.oci.hardCodedKeySupplier}
    authorization:
      service-name: helidon-tagging-example
      root-cert-path: /etc/oci-pki/ca-bundle.pem
  identity-client:
    region: us-ashburn-1
  tagging:
    emit-metrics: false

declarative:
  ignore-incubating: true
