<?xml version="1.0" encoding="UTF-8"?>
<project xmlns="http://maven.apache.org/POM/4.0.0"
         xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"
         xsi:schemaLocation="http://maven.apache.org/POM/4.0.0 https://maven.apache.org/xsd/maven-4.0.0.xsd">
    <modelVersion>4.0.0</modelVersion>
    <parent>
        <groupId>com.oracle.helidon.oci</groupId>
        <artifactId>helidon-oci-common-project</artifactId>
        <version>1.0-SNAPSHOT</version>
        <relativePath>../pom.xml</relativePath>
    </parent>

    <artifactId>helidon-oci-tls-pki</artifactId>
    <version>1.0-SNAPSHOT</version>

    <name>PKI Certificates Service Integration</name>
    <description>https://confluence.oci.oraclecorp.com/display/DEVCENTRAL/PKI+and+Certificate+Basics</description>

<!--    <properties>-->
<!--        <mainClass>io.helidon.integrations.oci.tls.pki</mainClass>-->
<!--    </properties>-->

    <dependencies>
<!--        <dependency>-->
<!--            <groupId>com.oracle.oci.sdk</groupId>-->
<!--            <artifactId>oci-java-sdk-common</artifactId>-->
<!--            &lt;!&ndash; todo &ndash;&gt;-->
<!--&lt;!&ndash;            <version>2.39.0</version>&ndash;&gt;-->
<!--            <version>3.23.2</version>-->
<!--        </dependency>-->
<!--        <dependency>-->
<!--            <groupId>javax.ws.rs</groupId>-->
<!--            <artifactId>javax.ws.rs-api</artifactId>-->
<!--            <version>2.0</version>-->
<!--        </dependency>-->

<!--        <dependency>-->
<!--&lt;!&ndash;            <groupId>com.oracle.pic.vault</groupId>&ndash;&gt;-->
<!--            <groupId>com.oracle.wlms</groupId>-->
<!--            <artifactId>oci-vault-java-sdk</artifactId>-->
<!--&lt;!&ndash;            &lt;!&ndash; todo &ndash;&gt;&ndash;&gt;-->
<!--&lt;!&ndash;            <version>2.0.3</version>&ndash;&gt;-->
<!--        </dependency>-->

        <!-- TODO -->
        <dependency>
<!--            <groupId>com.oracle.wlms</groupId>-->
<!--            <artifactId>oci-vault-java-sdk</artifactId>-->
            <groupId>com.oracle.pic.vault</groupId>
            <artifactId>vault-java-sdk</artifactId>
            <version>0.0.1-SNAPSHOT</version>
        </dependency>

        <dependency>
            <groupId>com.oracle.helidon.oci</groupId>
            <artifactId>helidon-repackaged-oci-vault-user-java-client</artifactId>
        </dependency>

        <!--        <dependency>-->
<!--            <groupId>com.oracle.pic.secinf</groupId>-->
<!--            <artifactId>secret-service-cp-java-client</artifactId>-->
<!--            <version>${version.lib.oci-ssv2}</version>-->
<!--&lt;!&ndash;            <exclusions>&ndash;&gt;-->
<!--&lt;!&ndash;                <exclusion>&ndash;&gt;-->
<!--&lt;!&ndash;                    <groupId>javax.ws.rs</groupId>&ndash;&gt;-->
<!--&lt;!&ndash;                    <artifactId>javax.ws.rs-api</artifactId>&ndash;&gt;-->
<!--&lt;!&ndash;                </exclusion>&ndash;&gt;-->
<!--&lt;!&ndash;            </exclusions>&ndash;&gt;-->
<!--        </dependency>-->

<!--        <dependency>-->
<!--            <groupId>io.helidon.integrations.oci</groupId>-->
<!--            <artifactId>helidon-integrations-oci-tls-certificates</artifactId>-->
<!--        </dependency>-->

        <!-- needed to actually use OCI SDK -->
        <dependency>
            <groupId>com.oracle.oci.sdk</groupId>
            <artifactId>oci-java-sdk-common-httpclient-jersey3</artifactId>
        </dependency>


        <dependency>
            <groupId>org.projectlombok</groupId>
            <artifactId>lombok</artifactId>
            <version>1.18.28</version>
        </dependency>

<!--        <dependency>-->
<!--            <groupId>jakarta.ws.rs</groupId>-->
<!--            <artifactId>jakarta.ws.rs-api</artifactId>-->
<!--        </dependency>-->

        <dependency>
            <groupId>org.slf4j</groupId>
            <artifactId>slf4j-jdk14</artifactId>
<!--            <scope>test</scope>-->
        </dependency>

        <dependency>
            <groupId>org.junit.jupiter</groupId>
            <artifactId>junit-jupiter-api</artifactId>
            <scope>test</scope>
        </dependency>
        <dependency>
            <groupId>org.hamcrest</groupId>
            <artifactId>hamcrest-core</artifactId>
            <scope>test</scope>
        </dependency>
    </dependencies>

    <build>
        <plugins>
<!--            <plugin>-->
<!--                <groupId>io.helidon.build-tools</groupId>-->
<!--                <artifactId>helidon-services-plugin</artifactId>-->
<!--            </plugin>-->
<!--            <plugin>-->
<!--                <groupId>org.apache.maven.plugins</groupId>-->
<!--                <artifactId>maven-enforcer-plugin</artifactId>-->
<!--            </plugin>-->
            <plugin>
                <groupId>org.apache.maven.plugins</groupId>
                <artifactId>maven-dependency-plugin</artifactId>
                <executions>
                    <execution>
                        <id>copy-libs</id>
                    </execution>
                </executions>
            </plugin>
        </plugins>
    </build>
</project>
