# https://confluence.oci.oraclecorp.com/display/BLD/Build+Service+ocibuild.conf+Reference+Guide
# To use the OCI Build Service you place a file name ocibuild.conf at the root of your git repo.
# This file, written using the HOCON syntax, will cause a build to automatically be triggered when commits are pushed to your repo.
# The ocibuild.conf file also determines how build service executes the build commands on the source code in your repo.
# For more information about configuring ocibuild.conf follow the above link
# Where is my build: https://devops.oci.oraclecorp.com/build

runnerTag: latest
name: oracle-swagger-maven-plugin
team: Pegasus
phoneBookId: pegasus
description: Service code generation.

majorversion: 1
minorversion: 5
shortversion: ${majorversion}.${minorversion}
# BuildService will expand ${?BLD_SNAPSHOT_SUFFIX} to -SNAPSHOT, for snapshot branches.
# Note that incase you are not setting the version using the version property,
# ensure that -SNAPSHOT suffix is present to enable publish support to snapshot repository.
version: ${shortversion}${?BLD_BRANCH_SUFFIX}.${BLD_NUMBER}${?BLD_SNAPSHOT_SUFFIX}

triggerOnCommitBranches: ["master", "pull-requests"]
releaseBranches: ["master"]
# For all branches specified using snapshotBranches, BuildService will expand ${?BLD_SNAPSHOT_SUFFIX} to -SNAPSHOT
# which can be used to add the -SNAPSHOT suffix to the version.
snapshotBranches: ["pull-requests", "PEG-*"]
initialBuildNumber: {
    "master": 20
}
slackChannels: ["#oci_pegasus_alerts"]

# bitbucketTag (optional): Creates a unique tag on the commit when a build from a release branch (see releaseBranches) completes.
# In order to authorize tag creation, provide write permission to the service account build_service_role under repository settings in the bitbucket UI.
# Also as tags are unique in a repo, creating another tag with the same name is not possible in the repo.
bitbucketTag: {
  "enabled": true,
  "tagName": ${version},
  "description": "Build Service Created Tag"
}
authCompartmentOcid: ocid1.compartment.oc1..aaaaaaaai4vbgpwoptct4i75t26mpjoa446wslh4u7qcr5xd5wmwejutbmuq

steps: [
    {
        name: compilesource
        type: maven
        javaVersion: jdk-17
        runnerImage: build-runner-maven-graalvm22-jdk17
        mavenCommands: [
            { goal: "versions:set", args: "--global-toolchains build_config/toolchains.xml -DnewVersion="${version}" -DprocessAllModules=true" },
            { goal: "verify", args: "--global-toolchains build_config/toolchains.xml -Dorg.slf4j.simpleLogger.showDateTime=true -Dorg.slf4j.simpleLogger.dateTimeFormat=HH:mm:ss.SSS" }
        ]
        artifacts: [
            "**"
        ]
    },
    {
      name: publish_maven_artifacts
      type: publishmaven
      dependsOn: compilesource
      repository: commons-release-maven-local
      # Note: Snapshot builds go into pegasus-snapshot-maven-local repository, not commons-snapshot-maven-local.
      snapshotRepository: pegasus-snapshot-maven-local
    },
]
