<?xml version="1.0" encoding="UTF-8"?>
<!--
    Copyright (c) 2026 Oracle and/or its affiliates.
-->

<project xmlns="http://maven.apache.org/POM/4.0.0"
        xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"
        xsi:schemaLocation="http://maven.apache.org/POM/4.0.0 http://maven.apache.org/xsd/maven-4.0.0.xsd">
    <modelVersion>4.0.0</modelVersion>
    <!-- Parent pom defines some properties (like helidon.oci.version) and configures plugins -->
    <parent>
        <groupId>com.oracle.helidon.oci</groupId>
        <artifactId>helidon-oci-project</artifactId>
        <version>2.0.0-SNAPSHOT</version>
    </parent>

    <artifactId>helidon-oci-examples-project</artifactId>
    <name>Helidon Talon Examples Project</name>
    <packaging>pom</packaging>

    <modules>
        <module>audit</module>
        <module>identity</module>
        <module>limits</module>
        <module>metrics</module>
        <module>request-id</module>
        <module>secret-service</module>
        <module>splat</module>
        <module>store</module>
        <module>tagging</module>
        <module>workflow</module>
        <module>data-plane</module>
        <module>oci-openapi-generator</module>
    </modules>
</project>
