<project xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance" xmlns="http://maven.apache.org/POM/4.0.0"
        xsi:schemaLocation="http://maven.apache.org/POM/4.0.0 https://maven.apache.org/xsd/maven-4.0.0.xsd">
    <modelVersion>4.0.0</modelVersion>
    <!-- TODO - see https://jira.oci.oraclecorp.com/browse/WLMS-703 -->
    <parent>
        <groupId>io.helidon.applications</groupId>
        <artifactId>helidon-applications</artifactId>
        <version>2.6.4</version>
        <relativePath/>
    </parent>
    <groupId>com.oracle.helidon.oci</groupId>
    <artifactId>helidon-oci-dependencies</artifactId>
    <version>1.0-SNAPSHOT</version>
    <packaging>pom</packaging>

    <name>Helidon OCI Native Dependencies</name>
    <description>Maven dependency management for Helidon OCI native applications</description>

    <properties>
        <!-- Versions for libraries used in build -->
        <!-- <oci-java-sdk-version>${version.lib.oci}</oci-java-sdk-version>-->
        <oci-java-sdk-version>3.28.1</oci-java-sdk-version>

        <!-- <oci-internal-bom-version>2.0.188</oci-internal-bom-version>-->
        <oracle-identity-version>3.0.228</oracle-identity-version>
        <oracle-identity-common-version>2.1.0.465</oracle-identity-common-version>
<!--        <oracle-identity-policy-version>3.1.194</oracle-identity-policy-version>-->
<!--        <oracle-identity-metadata-version>1.0.31</oracle-identity-metadata-version>-->
        <commons-request-id-version>1.1.45</commons-request-id-version>

        <!-- 2.0.3 relies on oci-java-sdk 3.x(line 36), we are going to stay on this version before we update java-sdk -->
        <vault-java-sdk-version>2.0.2</vault-java-sdk-version>
        <vault-user-java-client-version>1.0.1</vault-user-java-client-version>
        <secret-service-cp-java-client-version>1.1.4</secret-service-cp-java-client-version>

        <version.lib.mockito>2.23.4</version.lib.mockito>

        <version.plugin.helidon-build-tools>3.0.5</version.plugin.helidon-build-tools>
        <version.plugin.helidon-build-tools.enforcer>4.0.0</version.plugin.helidon-build-tools.enforcer>
        <version.plugin.lombok-maven-plugin>1.18.20.0</version.plugin.lombok-maven-plugin>
        <version.plugin.maven-build-helper-plugin>3.0.0</version.plugin.maven-build-helper-plugin>
        <version.plugin.maven-directory-plugin>1.0</version.plugin.maven-directory-plugin>
        <version.plugin.maven-enforcer-plugin>3.4.1</version.plugin.maven-enforcer-plugin>
        <version.plugin.maven-exec-plugin>3.1.0</version.plugin.maven-exec-plugin>
        <version.plugin.maven-javadoc-plugin>2.10.4</version.plugin.maven-javadoc-plugin>
        <version.plugin.maven-versions-plugin>2.16.1</version.plugin.maven-versions-plugin>
    </properties>

    <dependencyManagement>
        <dependencies>
            <!-- TODO - see https://jira.oci.oraclecorp.com/browse/WLMS-703 -->
            <!-- See https://bitbucket.oci.oraclecorp.com/projects/PEG/repos/oci-internal-dependency-management/browse/oci-internal-bom/pom.xml -->
<!--            <dependency>-->
<!--                <groupId>com.oracle.pic.sfw</groupId>-->
<!--                <artifactId>oci-internal-bom</artifactId>-->
<!--                <version>${oci-internal-bom-version}</version>-->
<!--                <type>pom</type>-->
<!--                <scope>import</scope>-->
<!--            </dependency>-->
            <!-- Identity
                    Confluence: https://confluence.oci.oraclecorp.com/x/GV0cB
                    Phonebook link: https://devops.oci.oraclecorp.com/phonebook/identity-cloud-service
                    https://artifactory.oci.oraclecorp.com/libs-release/com/oracle/pic/identity/authorization/sdk/
            -->
            <dependency>
                <groupId>com.oracle.pic.identity.authorization</groupId>
                <artifactId>sdk</artifactId>
                <version>${oracle-identity-version}</version>
                <exclusions>
                    <exclusion>
                        <groupId>javax.annotation</groupId>
                        <artifactId>javax.annotation-api</artifactId>
                    </exclusion>
                    <exclusion>
                        <groupId>com.oracle.pic.identity.policy</groupId>
                        <artifactId>protocols</artifactId>
                    </exclusion>
                    <exclusion>
                        <groupId>javax.inject</groupId>
                        <artifactId>javax.inject</artifactId>
                    </exclusion>
                    <exclusion>
                        <groupId>javax.validation</groupId>
                        <artifactId>validation-api</artifactId>
                    </exclusion>
                    <exclusion>
                        <groupId>javax.servlet</groupId>
                        <artifactId>javax.servlet-api</artifactId>
                    </exclusion>
                </exclusions>
            </dependency>
            <dependency>
                <groupId>com.oracle.pic.identity</groupId>
                <artifactId>common</artifactId>
                <version>${oracle-identity-common-version}</version>
                <exclusions>
                    <exclusion>
                        <groupId>com.oracle.pic.identity.authorization</groupId>
                        <artifactId>common</artifactId>
                    </exclusion>
                    <exclusion>
                        <groupId>com.oracle.pic.identity</groupId>
                        <artifactId>common</artifactId>
                    </exclusion>
                    <exclusion>
                        <groupId>com.oracle.pic.identity.authentication</groupId>
                        <artifactId>authentication-common</artifactId>
                    </exclusion>
                    <exclusion>
                        <groupId>com.oracle.pic.identity.authentication</groupId>
                        <artifactId>authentication-signed-request-common</artifactId>
                    </exclusion>
                    <exclusion>
                        <groupId>com.oracle.pic.identity.authentication</groupId>
                        <artifactId>authentication-signed-request-verification</artifactId>
                    </exclusion>
                    <exclusion>
                        <groupId>com.oracle.pic.identity.authentication</groupId>
                        <artifactId>authentication-authenticator</artifactId>
                    </exclusion>
                    <exclusion>
                        <groupId>com.oracle.pic.identity.authentication</groupId>
                        <artifactId>authentication-signed-request-generation</artifactId>
                    </exclusion>
                    <exclusion>
                        <groupId>com.oracle.pic.identity.authentication</groupId>
                        <artifactId>authentication-token-common</artifactId>
                    </exclusion>
                    <exclusion>
                        <groupId>com.oracle.pic.identity.authentication</groupId>
                        <artifactId>authentication-token-generation</artifactId>
                    </exclusion>
                    <exclusion>
                        <groupId>com.oracle.pic.identity.authentication</groupId>
                        <artifactId>authentication-token-verification</artifactId>
                    </exclusion>
                    <!--com.oracle.pic.identity:common:2.0.0.427 has conflicts with itself-->
                    <exclusion>
                        <groupId>com.oracle.pic.platform.common</groupId>
                        <artifactId>platform-common-lib</artifactId>
                    </exclusion>
                    <!-- com.oracle.pic.identity:common:2.1.0.459 conflicts with com.oracle.pic.identity.authorization:sdk:2.1.194 -->
                    <exclusion>
                        <groupId>com.oracle.pic.flightssettings</groupId>
                        <artifactId>flight-setting</artifactId>
                    </exclusion>
                </exclusions>
            </dependency>
            <dependency>
                <groupId>com.oracle.pic.commons</groupId>
                <artifactId>request-id</artifactId>
                <version>${commons-request-id-version}</version>
            </dependency>
            <!-- Secret Service
                   Confluence: https://confluence.oci.oraclecorp.com/x/tajZ
                   Phonebook link: https://devops.oci.oraclecorp.com/phonebook/secret-management-service
                 -->
            <dependency>
                <groupId>com.oracle.pic.vault</groupId>
                <artifactId>vault-java-sdk</artifactId>
                <version>${vault-java-sdk-version}</version>
            </dependency>
            <dependency>
                <groupId>com.oracle.pic.vault</groupId>
                <artifactId>vault-user-java-client</artifactId>
                <version>${vault-user-java-client-version}</version>
            </dependency>
            <dependency>
                <groupId>com.oracle.pic.secinf</groupId>
                <artifactId>secret-service-cp-java-client</artifactId>
                <version>${secret-service-cp-java-client-version}</version>
            </dependency>

            <!-- overrides from parent io.helidon bom -->
            <dependency>
                <groupId>com.oracle.oci.sdk</groupId>
                <artifactId>oci-java-sdk-common</artifactId>
                <version>${oci-java-sdk-version}</version>
                <exclusions>
                    <exclusion>
                        <groupId>org.bouncycastle</groupId>
                        <artifactId>*</artifactId>
                    </exclusion>
                    <exclusion>
                        <groupId>org.apache.commons</groupId>
                        <artifactId>commons-lang3</artifactId>
                    </exclusion>
                    <exclusion>
                        <groupId>org.glassfish.hk2</groupId>
                        <artifactId>hk2-locator</artifactId>
                    </exclusion>
                    <exclusion>
                        <groupId>commons-io</groupId>
                        <artifactId>commons-io</artifactId>
                    </exclusion>
                    <exclusion>
                        <groupId>commons-codec</groupId>
                        <artifactId>commons-codec</artifactId>
                    </exclusion>
                </exclusions>
            </dependency>
            <dependency>
                <groupId>com.oracle.oci.sdk</groupId>
                <artifactId>oci-java-sdk-common-httpclient</artifactId>
                <version>${oci-java-sdk-version}</version>
            </dependency>
            <dependency>
                <groupId>com.oracle.oci.sdk</groupId>
                <artifactId>oci-java-sdk-common-httpclient-jersey3</artifactId>
                <version>${oci-java-sdk-version}</version>
            </dependency>

            <!-- our module definitions -->
            <dependency>
                <groupId>com.oracle.helidon.oci</groupId>
                <artifactId>helidon-oci-error-code</artifactId>
                <version>${project.version}</version>
            </dependency>
            <dependency>
                <groupId>com.oracle.helidon.oci</groupId>
                <artifactId>helidon-oci-request-id</artifactId>
                <version>${project.version}</version>
            </dependency>
            <dependency>
                <groupId>com.oracle.helidon.oci</groupId>
                <artifactId>helidon-oci-swagger-maven-plugin</artifactId>
                <version>${project.version}</version>
            </dependency>

            <!-- our repackaged module definitions -->
            <dependency>
                <groupId>com.oracle.helidon.oci</groupId>
                <artifactId>helidon-repackaged-oci-authorization-sdk</artifactId>
                <version>${project.version}</version>
            </dependency>
            <dependency>
                <groupId>com.oracle.helidon.oci</groupId>
                <artifactId>helidon-repackaged-oci-vault-java-sdk</artifactId>
                <version>${project.version}</version>
            </dependency>
            <dependency>
                <groupId>com.oracle.helidon.oci</groupId>
                <artifactId>helidon-repackaged-oci-vault-user-java-client</artifactId>
                <version>${project.version}</version>
            </dependency>
        </dependencies>
    </dependencyManagement>

    <build>
        <pluginManagement>
            <plugins>
                <plugin>
                    <groupId>org.codehaus.mojo</groupId>
                    <artifactId>versions-maven-plugin</artifactId>
                    <version>${version.plugin.maven-versions-plugin}</version>
                </plugin>
                <plugin>
                    <groupId>io.helidon.build-tools</groupId>
                    <artifactId>helidon-services-plugin</artifactId>
                    <version>${version.plugin.helidon-build-tools}</version>
                    <configuration>
                        <mode>fail</mode>
                    </configuration>
                    <executions>
                        <execution>
                            <id>generate-meta-inf-services</id>
                            <phase>compile</phase>
                            <goals>
                                <goal>services</goal>
                            </goals>
                        </execution>
                    </executions>
                </plugin>
                <plugin>
                    <groupId>org.apache.maven.plugins</groupId>
                    <artifactId>maven-enforcer-plugin</artifactId>
                    <version>${version.plugin.maven-enforcer-plugin}</version>
                    <dependencies>
                        <!-- dependencies to your artifact contains rule implementation -->
                        <dependency>
                            <groupId>io.helidon.build-tools</groupId>
                            <artifactId>helidon-build-maven-enforcer-rules</artifactId>
                            <version>${version.plugin.helidon-build-tools.enforcer}</version>
                        </dependency>
                    </dependencies>
                    <executions>
                        <execution>
                            <id>enforce-jakarta-dependencies</id>
                            <goals>
                                <goal>enforce</goal>
                            </goals>
                            <configuration>
                                <rules>
                                    <helidonDependenciesRule>
                                        <namespace>JAVAX</namespace>
                                        <excludedGavRegExs/>
                                    </helidonDependenciesRule>
                                </rules>
                            </configuration>
                        </execution>
                    </executions>
                </plugin>
                <plugin>
                    <groupId>org.commonjava.maven.plugins</groupId>
                    <artifactId>directory-maven-plugin</artifactId>
                    <version>${version.plugin.maven-directory-plugin}</version>
                </plugin>
                <plugin>
                    <groupId>org.codehaus.mojo</groupId>
                    <artifactId>exec-maven-plugin</artifactId>
                    <version>${version.plugin.maven-exec-plugin}</version>
                </plugin>
                <plugin>
                    <groupId>org.codehaus.mojo</groupId>
                    <artifactId>build-helper-maven-plugin</artifactId>
                    <version>${version.plugin.maven-build-helper-plugin}</version>
                </plugin>
            </plugins>
        </pluginManagement>
        <plugins>
            <plugin>
                <groupId>org.commonjava.maven.plugins</groupId>
                <artifactId>directory-maven-plugin</artifactId>
                <executions>
                    <execution>
                        <id>generate-top-parent-basedir</id>
                        <goals>
                            <goal>highest-basedir</goal>
                        </goals>
                        <phase>validate</phase>
                        <configuration>
                            <property>top.parent.basedir</property>
                        </configuration>
                    </execution>
                </executions>
            </plugin>
            <plugin>
                <groupId>org.codehaus.mojo</groupId>
                <artifactId>versions-maven-plugin</artifactId>
                <executions>
                    <execution>
                        <phase>install</phase>
                        <goals>
                            <goal>display-property-updates</goal>
                        </goals>
                        <configuration>
                            <!--suppress UnresolvedMavenProperty -->
                            <rulesUri>file://${top.parent.basedir}/build_config/maven-version-rules.xml</rulesUri>
                            <allowIncrementalUpdates>true</allowIncrementalUpdates>
                            <allowMinorUpdates>true</allowMinorUpdates>
                            <allowMajorUpdates>true</allowMajorUpdates>

                            <!-- This files tracks dependency updates that are due -->
                            <!-- Remove the following line if you wish to disable this tracking file feature -->
                            <outputFile>../bom-dependency-versions.txt</outputFile>

                            <!-- SNAPSHOT versions of the bom should NOT be used in production -->
                            <allowSnapshots>false</allowSnapshots>

                            <!-- Version control already keeps history of the pom file changes -->
                            <generateBackupPoms>false</generateBackupPoms>

                            <!-- We don't want to scan the dependencies within the bom -->
                            <!-- <processDependencyManagementTransitive>false</processDependencyManagementTransitive>-->
                        </configuration>
                    </execution>
                </executions>
                <inherited>false</inherited> <!-- We only want to run this plugin in this pom, and not every module. -->
            </plugin>
        </plugins>
    </build>
</project>