<?xml version="1.0" encoding="UTF-8"?>
<!--
    Copyright (c) 2023, 2025 Oracle and/or its affiliates.
-->

<project xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance" xmlns="http://maven.apache.org/POM/4.0.0"
        xsi:schemaLocation="http://maven.apache.org/POM/4.0.0 https://maven.apache.org/xsd/maven-4.0.0.xsd">
    <modelVersion>4.0.0</modelVersion>
    <parent>
        <groupId>com.oracle.helidon.oci</groupId>
        <artifactId>helidon-oci-bom</artifactId>
        <version>2.0.0-SNAPSHOT</version>
        <relativePath>../bom/pom.xml</relativePath>
    </parent>
    <artifactId>helidon-oci-dependencies</artifactId>
    <packaging>pom</packaging>

    <name>Helidon OCI Native Dependencies</name>
    <description>Maven dependency management for Helidon OCI native applications</description>

    <properties>
        <oracle-internal-commons-request-id-version>1.1.55</oracle-internal-commons-request-id-version>
    </properties>

    <dependencyManagement>
        <dependencies>
            <!-- TODO: we should (eventually) discontinue usage of this -->
            <!-- https://devops.oci.oraclecorp.com/devops-coderepository/namespaces/axuxirvibvvo/projects/PEG/repositories/request-id -->
            <dependency>
                <groupId>com.oracle.pic.commons</groupId>
                <artifactId>request-id</artifactId>
                <version>${oracle-internal-commons-request-id-version}</version>
            </dependency>
        </dependencies>
    </dependencyManagement>
</project>
