<?xml version="1.0" encoding="UTF-8"?>
<!--
    Copyright (c) 2025 Oracle and/or its affiliates.
-->
<project xmlns="http://maven.apache.org/POM/4.0.0"
        xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"
        xsi:schemaLocation="http://maven.apache.org/POM/4.0.0 https://maven.apache.org/xsd/maven-4.0.0.xsd">
    <modelVersion>4.0.0</modelVersion>
    <parent>
        <groupId>com.oracle.helidon.oci</groupId>
        <artifactId>helidon-repackaged-oci</artifactId>
        <version>1.2.1-SNAPSHOT</version>
        <relativePath>../pom.xml</relativePath>
    </parent>
    <artifactId>helidon-repackaged-oci-workflow-service-java-client</artifactId>
    <version>1.2.1-SNAPSHOT</version>
    <packaging>jar</packaging>

    <name>Helidon OCI Repackaged OCI Workflow Service Java Client</name>

    <properties>
        <spotbugs.exclude>etc/spotbugs/exclude.xml</spotbugs.exclude>
        <!--
              This is the file name of the preprocessed spec in the artifact.
              It depends on which 'enabled group files' you have had when the spec artifact was built,
              but the 'release' directory should always exist, and the file inside it should have
              the same name as the spec file in your 'src/spec' directory.

              The 'bmc-sdk-swagger-maven-plugin-example-api-spec' artifact built by the ../example-api-spec
              project contains the 'src/enabled-conditional-groups/release.txt' and
              'src/enabled-conditional-groups/internal.txt' files. The Swagger spec is called
              'bmc-sdk-swagger-maven-plugin-example-api-spec.yaml'. Therefore, the two options for
              this setting are 'release/bmc-sdk-swagger-maven-plugin-example-api-spec.yaml' and
              'internal/bmc-sdk-swagger-maven-plugin-example-api-spec.yaml'.
        -->
        <codegen.spec.name>workflow-service-interface.yaml</codegen.spec.name>

        <!--
              This is the Java package where your generated classes will go.
              If your service is called 'example', we suggest 'com.oracle.bmc.example'.
        -->
        <codegen.base.package.name>com.oracle.pic.workflow.client.v1</codegen.base.package.name>

        <!--
              This is the service endpoint in the REST URI.
              If your service can be found at 'example.us-phoenix-1.oraclecloud.com' in PHX,
              then this value should be 'example'.
        -->
        <codegen.endpoint>127.0.0.1</codegen.endpoint>

        <!--
              Probably doesn't have to be changed. Set to 'false' if you don't want waiters
              for resources with 'lifecycleState'.
        -->
        <codegen.generate.waiters>false</codegen.generate.waiters>

        <!--
              'INTERNAL' means 'generate everything'. Probably don't have to change this.
              This is related to the 'x-obmcs-internal-only' and 'x-obmcs-preview-only' flags,
              which we are trying to get away from.
              See https://confluence.oci.oraclecorp.com/pages/viewpage.action?pageId=12205175
        -->

        <codegen.specGenerationType>INTERNAL</codegen.specGenerationType>
        <!-- End: Fill these out with values for your service -->
        <!-- ================================================ -->

        <!-- Disable explicit-null tracking for our generated clients.  This causes
            issues for customers that want to store any of our generated client model
            objects directly into kiev (a bad-practice for sure, but wide-spread for
            customers coming from our old hand-written client -->
        <codegen.use.explicitly.set.filter>false</codegen.use.explicitly.set.filter>
    </properties>

    <dependencies>
        <dependency>
            <groupId>com.oracle.pic.workflow.client</groupId>
            <artifactId>workflow-service-java-client</artifactId>
            <scope>provided</scope>
        </dependency>
        <dependency>
            <groupId>com.oracle.pic.workflow</groupId>
            <artifactId>workflow-service-spec</artifactId>
        </dependency>
    </dependencies>

    <build>
        <plugins>
            <plugin>
                <groupId>com.oracle.helidon.oci</groupId>
                <artifactId>helidon-oci-repackage-plugin</artifactId>
                <version>1.2.1-SNAPSHOT</version>
                <executions>
                    <execution>
                        <goals>
                            <goal>repackage-oci-libs</goal>
                        </goals>
                        <phase>initialize</phase>
                    </execution>
                </executions>
                <configuration>
                    <artifacts>
                        <artifact>
                            <groupId>com.oracle.pic.workflow.client</groupId>
                            <artifactId>workflow-service-java-client</artifactId>
                            <exclusions>
                                <!-- Drop original workflow generated content -->
                                <exclusion>com/oracle/pic/workflow/client/v1/[^/]*\.class</exclusion>
                                <exclusion>com/oracle/pic/workflow/client/v1/model/[^/]*\.class</exclusion>
                                <exclusion>com/oracle/pic/workflow/client/v1/requests/[^/]*\.class</exclusion>
                                <exclusion>com/oracle/pic/workflow/client/v1/responses/[^/]*\.class</exclusion>
                                <exclusion>com/oracle/pic/workflow/client/v1/internal/http/[^/]*\.class</exclusion>
                            </exclusions>
                        </artifact>
                        <dependency>
                            <groupId>com.oracle.pic.workflow</groupId>
                            <artifactId>workflow-service-spec</artifactId>
                        </dependency>
                    </artifacts>
                </configuration>
            </plugin>
            <plugin>
                <groupId>com.oracle.bmc.sdk</groupId>
                <artifactId>bmc-sdk-swagger-maven-plugin</artifactId>
                <version>2.142-3.75.0</version>
                <executions>
                    <execution>
                        <id>java-sdk-spec</id>
                        <phase>generate-sources</phase>
                        <goals>
                            <goal>generate</goal>
                        </goals>
                        <configuration>
                            <language>oracle-java-sdk</language>
                            <specPath>${project.build.directory}/classes/${codegen.spec.name}</specPath>
                            <basePackage>${codegen.base.package.name}</basePackage>
                            <additionalProperties>
                                <serviceGroupEndpoint>${codegen.endpoint}</serviceGroupEndpoint>
                                <generateWaiters>${codegen.generate.waiters}</generateWaiters>
                                <useExplicitlySetFilter>${codegen.use.explicitly.set.filter}</useExplicitlySetFilter>
                            </additionalProperties>
                            <specGenerationType>${codegen.specGenerationType}</specGenerationType>
                            <isTestGenerationEnabled>false</isTestGenerationEnabled>
                            <isExpect100ContinueSupported>false</isExpect100ContinueSupported>
                        </configuration>
                    </execution>
                </executions>
            </plugin>
            <plugin>
                <groupId>org.codehaus.mojo</groupId>
                <artifactId>build-helper-maven-plugin</artifactId>
                <version>3.4.0</version>
                <executions>
                    <execution>
                        <id>import-swagger-client-sources</id>
                        <phase>generate-sources</phase>
                        <goals>
                            <goal>add-source</goal>
                        </goals>
                        <configuration>
                            <sources>
                                <source>${project.build.directory}/generated-sources/oracle-java-sdk-sources/</source>
                            </sources>
                        </configuration>
                    </execution>
                    <execution>
                        <id>import-swagger-client-resources</id>
                        <phase>generate-resources</phase>
                        <goals>
                            <goal>add-resource</goal>
                        </goals>
                        <configuration>
                            <resources>
                                <resource>
                                    <directory>${project.build.directory}/generated-sources/oracle-java-sdk-resources/</directory>
                                </resource>
                            </resources>
                        </configuration>
                    </execution>
                </executions>
            </plugin>
        </plugins>
    </build>
</project>
