<?xml version="1.0" encoding="UTF-8"?>
<!--
    Copyright (c) 2024, 2025 Oracle and/or its affiliates.
-->
<project xmlns="http://maven.apache.org/POM/4.0.0"
        xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"
        xsi:schemaLocation="http://maven.apache.org/POM/4.0.0 https://maven.apache.org/xsd/maven-4.0.0.xsd">
    <modelVersion>4.0.0</modelVersion>
    <parent>
        <groupId>com.oracle.helidon.oci</groupId>
        <artifactId>helidon-repackaged-oci</artifactId>
        <version>1.2.0-SNAPSHOT</version>
        <relativePath>../pom.xml</relativePath>
    </parent>
    <artifactId>helidon-repackaged-oci-splat-sdk</artifactId>
    <version>1.2.0-SNAPSHOT</version>
    <packaging>jar</packaging>

    <name>Helidon OCI Repackaged OCI splat-sdk</name>

    <properties>
        <spotbugs.skip>true</spotbugs.skip>
        <codegen.swagger.spec>${project.build.directory}/classes/api.yaml</codegen.swagger.spec>
        <codegen.base.package.name>com.oracle.pic.platform.splat.sdk.client.store</codegen.base.package.name>
        <codegen.endpoint>splat-store</codegen.endpoint>
        <codegen.generate.waiters>true</codegen.generate.waiters>
        <codegen.specGenerationType>INTERNAL</codegen.specGenerationType>
        <project.build.sourceEncoding>UTF-8</project.build.sourceEncoding>
        <codegen.use.explicitly.set.filter>true</codegen.use.explicitly.set.filter>
    </properties>

    <dependencies>
        <dependency>
            <groupId>com.oracle.pic.platform.splat.sdk</groupId>
            <artifactId>splat-sdk</artifactId>
            <scope>provided</scope>
        </dependency>
        <dependency>
            <groupId>com.oracle.pic.platform.splat</groupId>
            <artifactId>splat-store-spec</artifactId>
            <scope>provided</scope>
        </dependency>
        <dependency>
            <groupId>com.oracle.oci.internals.sdk</groupId>
            <artifactId>java-sdk-oci-internals-commons</artifactId>
        </dependency>
    </dependencies>

    <build>
        <plugins>
            <plugin>
                <groupId>com.oracle.helidon.oci</groupId>
                <artifactId>helidon-oci-repackage-plugin</artifactId>
                <version>1.2.0-SNAPSHOT</version>
                <executions>
                    <execution>
                        <goals>
                            <goal>repackage-oci-libs</goal>
                        </goals>
                        <phase>initialize</phase>
                    </execution>
                </executions>
                <configuration>
                    <artifacts>
                        <artifact>
                            <groupId>com.oracle.pic.platform.splat.sdk</groupId>
                            <artifactId>splat-sdk</artifactId>
                            <exclusions>
                                <!-- Drop original swagger generated content -->
                                <exclusion>com/oracle/pic/platform/splat/sdk/client/store/[^\.]*\.class</exclusion>
                            </exclusions>
                        </artifact>
                        <artifact>
                            <groupId>com.oracle.pic.platform.splat</groupId>
                            <artifactId>splat-store-spec</artifactId>
                            <!-- TODO:kec - repackage api.yaml so swagger plugin can access it -->
                        </artifact>
                    </artifacts>
                    <classes>
                        <class>
                            <name>SplatHelper</name>
                            <pkg>com.oracle.pic.platform.splat.sdk</pkg>
                            <references-mapping>
                                <mapping>
                                    <name>ExplicitlySetFilter</name>
                                    <pkg>com.oracle.bmc.http.internal</pkg>
                                    <targetPkg>com.oracle.oci.internals.sdk.http.internal</targetPkg>
                                </mapping>
                                <mapping>
                                    <name>ExplicitlySetBmcModel</name>
                                    <pkg>com.oracle.bmc.http.internal</pkg>
                                    <targetPkg>com.oracle.bmc.http.client.internal</targetPkg>
                                </mapping>
                            </references-mapping>
                        </class>
                    </classes>
                </configuration>
            </plugin>
            <plugin>
                <groupId>com.oracle.bmc.sdk</groupId>
                <artifactId>bmc-sdk-swagger-maven-plugin</artifactId>
                <version>${bmc-sdk-swagger-maven-plugin.version}</version>
                <executions>
                    <execution>
                        <id>java-sdk-spec</id>
                        <phase>generate-sources</phase>
                        <goals>
                            <goal>generate</goal>
                        </goals>
                        <configuration>
                            <language>oracle-java-sdk</language>
                            <specPath>${codegen.swagger.spec}</specPath>
                            <basePackage>${codegen.base.package.name}</basePackage>
                            <additionalProperties>
                                <!--
                                Note that this setting can only be used for endpoints following the
                                '<service>.<region>.oraclecloud.com' pattern. To use other endpoint formats,
                                specify the endpoint template in your spec.

                                See https://confluence.oci.oraclecorp.com/display/DEX/Service+Endpoint+Update
                                -->
                                <serviceGroupEndpoint>${codegen.endpoint}</serviceGroupEndpoint>
                                <generateWaiters>${codegen.generate.waiters}</generateWaiters>
                                <useExplicitlySetFilter>${codegen.use.explicitly.set.filter}
                                </useExplicitlySetFilter>
                            </additionalProperties>
                            <outputDir>${project.build.directory}/generated-sources/${codegen.base.package.name}
                            </outputDir>
                            <specGenerationType>${codegen.specGenerationType}</specGenerationType>
                            <isTestGenerationEnabled>false</isTestGenerationEnabled>
                        </configuration>
                    </execution>
                </executions>
            </plugin>

            <plugin>
                <groupId>org.codehaus.mojo</groupId>
                <artifactId>build-helper-maven-plugin</artifactId>
                <version>3.6.0</version>
                <executions>
                    <execution>
                        <id>add-source-root</id>
                        <phase>generate-sources</phase>
                        <goals>
                            <goal>add-source</goal>
                        </goals>
                        <configuration>
                            <sources>
                                <source>
                                    ${project.build.directory}/generated-sources/${codegen.base.package.name}/oracle-java-sdk-sources
                                </source>
                            </sources>
                        </configuration>
                    </execution>
                    <execution>
                        <id>add-specs</id>
                        <phase>generate-sources</phase>
                        <goals>
                            <goal>add-resource</goal>
                        </goals>
                        <configuration>
                            <resources>
                                <resource>
                                    <directory>${project.basedir}/../splat-store-parent/splat-store-spec/specs</directory>
                                    <targetPath>splat-store-spec</targetPath>
                                </resource>
                            </resources>
                        </configuration>
                    </execution>
                </executions>
            </plugin>
        </plugins>
    </build>

</project>