<?xml version="1.0" encoding="UTF-8"?>
<project xmlns="http://maven.apache.org/POM/4.0.0"
         xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"
         xsi:schemaLocation="http://maven.apache.org/POM/4.0.0 http://maven.apache.org/xsd/maven-4.0.0.xsd">
    <parent>
        <groupId>com.oracle.helidon.oci</groupId>
        <artifactId>helidon-oci-integration-tests</artifactId>
        <version>1.0-SNAPSHOT</version>
        <relativePath>../pom.xml</relativePath>
    </parent>
    <modelVersion>4.0.0</modelVersion>

    <artifactId>helidon-oci-dependencies-test</artifactId>
    <name>OCI Dependencies Test</name>
    <packaging>pom</packaging>
    <description>These ensure that downstream usages of our ${basedir}/dependencies/pom.xml will work properly</description>

    <build>
        <plugins>
            <!-- the enforcer is acting as our test here -->
            <plugin>
                <groupId>org.apache.maven.plugins</groupId>
                <artifactId>maven-enforcer-plugin</artifactId>
            </plugin>

            <plugin>
                <groupId>org.codehaus.mojo</groupId>
                <artifactId>versions-maven-plugin</artifactId>
                <executions>
                    <execution>
                        <phase>install</phase>
                        <goals>
                            <goal>display-property-updates</goal>
                        </goals>
                        <configuration>
                            <includeProperties>
                                helidon.version,
                                oci-java-sdk-version,
                                oracle-internal-authproxy-filter-version,
<!--                                oracle-internal-commons-core-version,-->
<!--                                oracle-internal-commons-core-resources-version,-->
                                oracle-internal-commons-metrics-lib-version,
                                oracle-internal-commons-metrics-reporter-version,
                                oracle-internal-commons-metrics-version,
                                oracle-internal-commons-request-id-version,
<!--                                oracle-internal-core-regions-version,-->
                                oracle-internal-exception-mapping-version,
                                oracle-internal-identity-common-version,
                                oracle-internal-identity-version,
                                oracle-internal-logging-version,
                                oracle-internal-vault-java-sdk-version,
                                oracle-internal-vault-user-api-spec-version,
                                oracle-internal-vault-user-java-client-version,
                                oracle-internal-secret-service-cp-java-client-version,
                            </includeProperties>
                            <!--suppress UnresolvedMavenProperty -->
                            <rulesUri>file://${top.parent.basedir}/build_config/maven-version-rules.xml</rulesUri>
                            <allowIncrementalUpdates>true</allowIncrementalUpdates>
                            <allowMinorUpdates>true</allowMinorUpdates>
                            <allowMajorUpdates>false</allowMajorUpdates>

                            <!-- This files tracks dependency updates that are due -->
                            <!-- Remove the following line if you wish to disable this tracking file feature -->
                            <outputFile>${top.parent.basedir}/bom-dependency-versions.txt</outputFile>

                            <!-- SNAPSHOT versions of the bom should NOT be used in production -->
                            <allowSnapshots>false</allowSnapshots>

                            <!-- Version control already keeps history of the pom file changes -->
                            <generateBackupPoms>false</generateBackupPoms>

                            <includeParent>true</includeParent>
                        </configuration>
                    </execution>
                </executions>
            </plugin>
        </plugins>
    </build>

</project>