/*
 * Copyright (c) 2023 Oracle and/or its affiliates.
 *
 * Licensed under the Apache License, Version 2.0 (the "License");
 * you may not use this file except in compliance with the License.
 * You may obtain a copy of the License at
 *
 *     http://www.apache.org/licenses/LICENSE-2.0
 *
 * Unless required by applicable law or agreed to in writing, software
 * distributed under the License is distributed on an "AS IS" BASIS,
 * WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
 * See the License for the specific language governing permissions and
 * limitations under the License.
 */

package com.oracle.helidon.oci.requestid;

import io.helidon.common.Weight;
import io.helidon.common.context.Contexts;
import io.helidon.http.Header;
import io.helidon.http.HeaderName;
import io.helidon.http.HeaderNames;
import io.helidon.http.HeaderValues;
import io.helidon.http.ServerRequestHeaders;
import io.helidon.logging.common.HelidonMdc;
import io.helidon.webserver.http.Filter;
import io.helidon.webserver.http.FilterChain;
import io.helidon.webserver.http.RoutingRequest;
import io.helidon.webserver.http.RoutingResponse;

import jakarta.ws.rs.container.PreMatching;

import static com.oracle.helidon.oci.requestid.OciRequestId.OCI_REQUEST_ID;

/**
 * Ensures all client requests include the opc-request-id header: which is either
 * received on the request or generated by this filter. Also makes the header value
 * available in the MDC context for logging, and to the Helidon context for general
 * processing of the request.
 */
@PreMatching
// after Context, before AccessLog
@Weight(1050)
class RequestIdServerFilter implements Filter {
    static final HeaderName OCI_REQUEST_ID_HEADER = HeaderNames.create(OCI_REQUEST_ID);

    @Override
    public void filter(FilterChain filterChain, RoutingRequest routingRequest, RoutingResponse routingResponse) {
        ServerRequestHeaders headers = routingRequest.headers();

        OciRequestId requestId;

        Header requestIdHeader;

        if (headers.contains(OCI_REQUEST_ID_HEADER)) {
            Header receivedHeader = headers.get(OCI_REQUEST_ID_HEADER);

            requestId = OciRequestId.parseUpstreamRequest(receivedHeader.getString());
            requestIdHeader = HeaderValues.create(OCI_REQUEST_ID_HEADER,
                                                  requestId.upstreamHeaderValue());
        } else {
            requestId = OciRequestId.generate();
            requestIdHeader = HeaderValues.create(OCI_REQUEST_ID_HEADER, requestId.upstreamHeaderValue());
        }

        routingRequest.header(requestIdHeader);

        // register requestId in useful contexts
        HelidonMdc.set(OCI_REQUEST_ID, requestId.upstreamHeaderValue());
        Contexts.context().ifPresent(c -> c.register(requestId));

        // must use the upstream header value, as this is the response to our client
        routingResponse.headers()
                .set(requestIdHeader);

        filterChain.proceed();
    }
}
