#
# Copyright (c) 2025 Oracle and/or its affiliates.
#

# -----------
# Build Image
# -----------
FROM ocr-docker-remote.artifactory.oci.oraclecorp.com/os/oraclelinux:9-slim as build

RUN microdnf install -y go-toolset

# Go build env
ENV CGO_ENABLED=0

WORKDIR /app

# Install source deps
COPY go.mod go.sum ./
RUN go mod download

# Copy source & build
COPY . .
RUN go build -v -ldflags '-s' -o /bin/ryuk
RUN chmod +x /bin/ryuk

# -----------------
# Distributed Image
# -----------------
FROM ocr-docker-remote.artifactory.oci.oraclecorp.com/os/oraclelinux:9-slim

RUN microdnf install -y ca-certificates

COPY --from=build /bin/ryuk /bin/ryuk
CMD ["/bin/ryuk"]
LABEL org.testcontainers.ryuk=true

