<?xml version="1.0" encoding="UTF-8"?>
<project xmlns="http://maven.apache.org/POM/4.0.0"
         xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"
         xsi:schemaLocation="http://maven.apache.org/POM/4.0.0 https://maven.apache.org/xsd/maven-4.0.0.xsd">
    <modelVersion>4.0.0</modelVersion>
    <parent>
        <groupId>com.oracle.helidon.oci</groupId>
        <artifactId>helidon-repackaged-oci</artifactId>
        <version>1.0-SNAPSHOT</version>
        <relativePath>../pom.xml</relativePath>
    </parent>
    <artifactId>helidon-repackaged-oci-vault-user-java-client</artifactId>
    <version>1.0-SNAPSHOT</version>

    <name>Repackaged: OCI vault-user-java-client</name>

    <!-- SEE https://bitbucket.oci.oraclecorp.com/projects/VAULT/repos/vault-user-java-client/pull-requests/30 -->

    <!--
       Unfortunately, we cannot use a different parent POM here
       than for the secret-service-cp-java-client (v2). What
       we would really want to do is point this at
       com.oracle.bmc.sdk.clients:bmc-sdk-java-client-parent:3.0.0.
       as parent.
       But then the Maven version set plugin (mvn version:set)
       would not update the version of this pom.xml file, and
       building in Build Service wouldn't work anymore (or anywhere
       where we need to set the version).
       Hence, the only solution here is to copy a lot from the
       3.0.0 parent at
       https://bitbucket.oci.oraclecorp.com/projects/SDK/repos/bmc-sdk-swagger/browse/bmc-sdk-clients/bmc-sdk-java-client-parent/pom.xml?at=refs%2Ftags%2F2.22-3.23.2
    -->

    <properties>
        <jakarta.annotation.version>2.1.1</jakarta.annotation.version>
        <lombok-maven-plugin.version>1.18.20.0</lombok-maven-plugin.version>
        <maven-dependency-plugin.version>2.10</maven-dependency-plugin.version>
        <maven-build-helper-maven-plugin.version>3.0.0</maven-build-helper-maven-plugin.version>
        <maven-javadoc-plugin.version>2.10.4</maven-javadoc-plugin.version>

        <vault-user-api-spec.version>1.0.1</vault-user-api-spec.version>
<!--        <oci-java-sdk-common.version>3.23.2</oci-java-sdk-common.version>-->

        <!-- Update this to the latest versions. -->
        <bmc-sdk-swagger-maven-plugin.version>2.22-3.23.2</bmc-sdk-swagger-maven-plugin.version>

        <codegen.base.package.name>com.oracle.pic.vault</codegen.base.package.name>
        <codegen.artifactory.groupId>com.oracle.pic.vault</codegen.artifactory.groupId>
        <codegen.artifactory.artifactId>vault-user-api-spec</codegen.artifactory.artifactId>
        <codegen.artifactory.version>1.0.1</codegen.artifactory.version>
        <codegen.spec.name>api.yaml</codegen.spec.name>
        <codegen.spec.dir>${project.build.directory}/specs</codegen.spec.dir>
        <codegen.spec.swagger>${codegen.spec.dir}/${codegen.spec.name}</codegen.spec.swagger>
        <codegen.generate.waiters>true</codegen.generate.waiters>
        <codegen.specGenerationType>INTERNAL</codegen.specGenerationType>
    </properties>

    <!-- see parent for the below -->
<!--    <dependencyManagement>-->
<!--        <dependencies>-->
<!--            <dependency>-->
<!--                <groupId>com.oracle.oci.sdk</groupId>-->
<!--                <artifactId>oci-java-sdk-common</artifactId>-->
<!--                <version>${oci-java-sdk-common.version}</version>-->
<!--                <exclusions>-->
<!--                    <exclusion>-->
<!--                        <groupId>org.bouncycastle</groupId>-->
<!--                        <artifactId>*</artifactId>-->
<!--                    </exclusion>-->
<!--                    <exclusion>-->
<!--                        <groupId>org.apache.commons</groupId>-->
<!--                        <artifactId>commons-lang3</artifactId>-->
<!--                    </exclusion>-->
<!--                    <exclusion>-->
<!--                        <groupId>org.glassfish.hk2</groupId>-->
<!--                        <artifactId>hk2-locator</artifactId>-->
<!--                    </exclusion>-->
<!--                    <exclusion>-->
<!--                        <groupId>commons-io</groupId>-->
<!--                        <artifactId>commons-io</artifactId>-->
<!--                    </exclusion>-->
<!--                    <exclusion>-->
<!--                        <groupId>commons-codec</groupId>-->
<!--                        <artifactId>commons-codec</artifactId>-->
<!--                    </exclusion>-->
<!--                </exclusions>-->
<!--            </dependency>-->
<!--        </dependencies>-->
<!--    </dependencyManagement>-->

    <dependencies>
        <dependency>
            <groupId>jakarta.annotation</groupId>
            <artifactId>jakarta.annotation-api</artifactId>
            <version>${jakarta.annotation.version}</version>
            <scope>provided</scope>
            <optional>true</optional>
        </dependency>

        <dependency>
            <groupId>com.oracle.oci.sdk</groupId>
            <artifactId>oci-java-sdk-common</artifactId>
        </dependency>
    </dependencies>

    <build>
        <pluginManagement>
            <plugins>
                <plugin>
                    <groupId>org.apache.maven.plugins</groupId>
                    <artifactId>maven-dependency-plugin</artifactId>
                    <version>${maven-dependency-plugin.version}</version>
                    <executions>
                        <execution>
                            <id>get-spec-from-artifactory</id>
                            <phase>initialize</phase>
                            <goals>
                                <goal>unpack</goal>
                            </goals>
                            <configuration>
                                <artifactItems>
                                    <artifactItem>
                                        <groupId>${codegen.artifactory.groupId}</groupId>
                                        <artifactId>${codegen.artifactory.artifactId}</artifactId>
                                        <version>${codegen.artifactory.version}</version>
                                        <type>jar</type>
                                        <includes>${codegen.spec.name}</includes>
                                        <outputDirectory>${codegen.spec.dir}</outputDirectory>
                                    </artifactItem>
                                </artifactItems>
                            </configuration>
                        </execution>
                    </executions>
                </plugin>
                <plugin>
                    <groupId>com.oracle.bmc.sdk</groupId>
                    <artifactId>bmc-sdk-swagger-maven-plugin</artifactId>
                    <version>${bmc-sdk-swagger-maven-plugin.version}</version>
                    <executions>
                        <execution>
                            <id>java-sdk-spec</id>
                            <phase>generate-sources</phase>
                            <goals>
                                <goal>generate</goal>
                            </goals>
                            <configuration>
                                <language>oracle-java-sdk</language>
                                <specPath>${codegen.spec.swagger}</specPath>
                                <basePackage>${codegen.base.package.name}</basePackage>
                                <additionalProperties>
                                    <!--
                                    Note that this setting can only be used for endpoints following the
                                    '<service>.<region>.oraclecloud.com' pattern. To use other endpoint formats,
                                    specify the endpoint template in your spec.

                                    See https://confluence.oci.oraclecorp.com/display/DEX/Service+Endpoint+Update
                                    -->
                                    <serviceGroupEndpoint>${codegen.endpoint}</serviceGroupEndpoint>
                                    <serviceGroupName>${codegen.serviceGroupName}</serviceGroupName>
                                    <generateWaiters>${codegen.generate.waiters}</generateWaiters>
                                    <generatePaginators>${codegen.generate.paginators}</generatePaginators>
                                    <useExplicitlySetFilter>${codegen.use.explicitly.set.filter}</useExplicitlySetFilter>
                                    <!-- Making SecretService client "non-regional".
                                         That sounds strange, because SecretService is definitely present
                                         in different regions. What this does, however, is remove the
                                         "setRegion" method, which doesn't work anyway, since (1) there
                                         are two different endpoints, depending on whether the request
                                         originates in the Customer Enclave or the Service Enclave; and
                                         (2) the endpoints do not use the domain names that the public
                                         OCI Java SDK assumes, like oraclecloud.com for OC1.

                                         See https://confluence.oci.oraclecorp.com/display/DEVCENTRAL/Java+SDK+to+Manage+Secrets+in+the+Control+Plane' -->
                                    <isRegionalClient.SecretService>false</isRegionalClient.SecretService>
                                </additionalProperties>
                                <outputDir>${project.build.directory}/generated-sources/${codegen.base.package.name}</outputDir>
                                <specGenerationType>${codegen.specGenerationType}</specGenerationType>
                                <isTestGenerationEnabled>${codegen.is.test.generation.enabled}</isTestGenerationEnabled>
                                <isExpect100ContinueSupported>${codegen.is.expect.100.continue.supported}</isExpect100ContinueSupported>
                            </configuration>
                        </execution>
                    </executions>
                </plugin>
                <plugin>
                    <groupId>org.codehaus.mojo</groupId>
                    <artifactId>build-helper-maven-plugin</artifactId>
                    <version>${maven-build-helper-maven-plugin.version}</version>
                    <executions>
                        <execution>
                            <id>add-source-root</id>
                            <phase>generate-sources</phase>
                            <goals>
                                <goal>add-source</goal>
                            </goals>
                            <configuration>
                                <sources>
                                    <source>${project.build.directory}/generated-sources/${codegen.base.package.name}/oracle-java-sdk-sources</source>
                                </sources>
                            </configuration>
                        </execution>
                    </executions>
                </plugin>
                <plugin>
                    <groupId>org.projectlombok</groupId>
                    <artifactId>lombok-maven-plugin</artifactId>
                    <version>${lombok-maven-plugin.version}</version>
                    <executions>
                        <execution>
                            <id>delombok</id>
                            <phase>process-sources</phase>
                            <goals>
                                <goal>delombok</goal>
                            </goals>
                            <configuration>
                                <addOutputDirectory>false</addOutputDirectory>
                                <!-- Only delombok for docs -->
                                <outputDirectory>target/generated-sources-for-docs/delombok</outputDirectory>
                                <sourceDirectory>${project.build.directory}/generated-sources/${codegen.base.package.name}/oracle-java-sdk-sources</sourceDirectory>
                                <encoding>UTF-8</encoding>
                                <formatPreferences>
                                    <javaLangAsFQN>skip</javaLangAsFQN>
                                    <generateDelombokComment>skip</generateDelombokComment>
                                    <generated>skip</generated>
                                    <indent>4</indent>
                                    <suppressWarnings>skip</suppressWarnings>
                                </formatPreferences>
                                <verbose>true</verbose>
                            </configuration>
                        </execution>
                    </executions>
                </plugin>
                <plugin>
                    <groupId>org.apache.maven.plugins</groupId>
                    <artifactId>maven-javadoc-plugin</artifactId>
                    <version>${maven-javadoc-plugin.version}</version>
                    <goals>
                        <goal>jar</goal>
                    </goals>
                    <executions>
                        <execution>
                            <id>aggregate</id>
                            <phase>package</phase>
                            <goals>
                                <goal>jar</goal>
                            </goals>
                        </execution>
                    </executions>
                    <configuration>
                        <doclet>ch.raffael.doclets.pegdown.PegdownDoclet</doclet>
                        <docletArtifact>
                            <groupId>ch.raffael.pegdown-doclet</groupId>
                            <artifactId>pegdown-doclet</artifactId>
                            <version>1.3</version>
                        </docletArtifact>
                        <useStandardDocletOptions>true</useStandardDocletOptions>
                        <aggregate>true</aggregate>
                        <minmemory>128m</minmemory>
                        <maxmemory>1024m</maxmemory>
                        <additionalparam>-Xdoclint:none -disable-highlight</additionalparam>
                        <sourcepath>target/generated-sources-for-docs/delombok</sourcepath>
                        <links>
                            <link>https://jax-rs-spec.java.net/nonav/2.0-rev-a/apidocs</link>
                            <link>https://docs.cloud.oracle.com/iaas/tools/java/latest</link>
                        </links>
                    </configuration>
                </plugin>
            </plugins>
        </pluginManagement>

        <plugins>
            <plugin>
                <groupId>org.apache.maven.plugins</groupId>
                <artifactId>maven-dependency-plugin</artifactId>
            </plugin>
            <plugin>
                <groupId>com.oracle.bmc.sdk</groupId>
                <artifactId>bmc-sdk-swagger-maven-plugin</artifactId>
            </plugin>
            <plugin>
                <groupId>org.codehaus.mojo</groupId>
                <artifactId>build-helper-maven-plugin</artifactId>
            </plugin>
            <plugin>
                <groupId>org.apache.maven.plugins</groupId>
                <artifactId>maven-compiler-plugin</artifactId>
            </plugin>
            <plugin>
                <groupId>org.apache.maven.plugins</groupId>
                <artifactId>maven-enforcer-plugin</artifactId>
            </plugin>
        </plugins>
    </build>

</project>
