<?xml version="1.0" encoding="UTF-8"?>
<project xmlns="http://maven.apache.org/POM/4.0.0"
         xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"
         xsi:schemaLocation="http://maven.apache.org/POM/4.0.0 https://maven.apache.org/xsd/maven-4.0.0.xsd">
    <modelVersion>4.0.0</modelVersion>
    <parent>
        <groupId>com.oracle.helidon.oci</groupId>
        <artifactId>helidon-repackaged-oci</artifactId>
        <version>1.0-SNAPSHOT</version>
        <relativePath>../pom.xml</relativePath>
    </parent>
    <artifactId>helidon-repackaged-oci-vault-user-java-client</artifactId>
    <version>1.0-SNAPSHOT</version>
    <packaging>jar</packaging>

    <name>Repackaged: OCI vault-user-java-client</name>

    <!-- See https://bitbucket.oci.oraclecorp.com/projects/VAULT/repos/vault-user-java-client/pull-requests/30 -->

    <properties>
        <!-- Overrides -->
        <version.lib.annotation-api>2.1.1</version.lib.annotation-api>

        <codegen.base.package.name>com.oracle.pic.vault</codegen.base.package.name>
        <codegen.artifactory.groupId>com.oracle.pic.vault</codegen.artifactory.groupId>
        <codegen.artifactory.artifactId>vault-user-api-spec</codegen.artifactory.artifactId>
        <codegen.artifactory.version>${oracle-internal-vault-user-api-spec-version}</codegen.artifactory.version>
        <codegen.spec.name>api.yaml</codegen.spec.name>
        <codegen.spec.dir>${project.build.directory}/specs</codegen.spec.dir>
        <codegen.spec.swagger>${codegen.spec.dir}/${codegen.spec.name}</codegen.spec.swagger>
        <codegen.generate.waiters>true</codegen.generate.waiters>
        <codegen.specGenerationType>INTERNAL</codegen.specGenerationType>
    </properties>

    <dependencies>
        <dependency>
            <groupId>jakarta.annotation</groupId>
            <artifactId>jakarta.annotation-api</artifactId>
            <version>${version.lib.annotation-api}</version>
            <scope>provided</scope>
            <optional>true</optional>
        </dependency>

        <dependency>
            <groupId>com.oracle.oci.sdk</groupId>
            <artifactId>oci-java-sdk-common</artifactId>
        </dependency>
    </dependencies>

    <build>
        <plugins>
            <plugin>
                <groupId>org.apache.maven.plugins</groupId>
                <artifactId>maven-dependency-plugin</artifactId>
            </plugin>
            <plugin>
                <groupId>com.oracle.bmc.sdk</groupId>
                <artifactId>bmc-sdk-swagger-maven-plugin</artifactId>
            </plugin>
            <plugin>
                <groupId>org.codehaus.mojo</groupId>
                <artifactId>build-helper-maven-plugin</artifactId>
            </plugin>
            <plugin>
                <groupId>org.apache.maven.plugins</groupId>
                <artifactId>maven-compiler-plugin</artifactId>
            </plugin>
            <plugin>
                <groupId>org.apache.maven.plugins</groupId>
                <artifactId>maven-enforcer-plugin</artifactId>
            </plugin>
        </plugins>
    </build>

</project>
