#
# Copyright (c) 2026 Oracle and/or its affiliates.
#
server:
  host: 0.0.0.0
  port: 8080

declarative:
  ignore-incubating: true

metrics:
  publishers:
    - type: oci
      enabled: true
      reporter:
        overlay:
          project: helidon-metrics-test-project
          fleet: helidon-metrics-test-fleet
          request-headers: { }
      default-dimensions: { }
      sample-interval: PT1S
