/*
 * Copyright (c) 2024, 2026 Oracle and/or its affiliates.
 */

package com.oracle.helidon.oci.requestid.webserver;

import io.helidon.http.Header;
import io.helidon.http.HeaderName;
import io.helidon.http.HeaderNames;
import io.helidon.http.HeaderValues;
import io.helidon.http.ServerRequestHeaders;
import io.helidon.logging.common.HelidonMdc;
import io.helidon.webserver.http.Filter;
import io.helidon.webserver.http.FilterChain;
import io.helidon.webserver.http.RoutingRequest;
import io.helidon.webserver.http.RoutingResponse;

import com.oracle.helidon.oci.requestid.OciRequestId;

/**
 * Ensures all client requests include the opc-request-id header: which is either
 * received on the request or generated by this filter. Also makes the header value
 * available in the MDC context for logging, and to the Helidon context for general
 * processing of the request.
 */
class RequestIdServerFilter implements Filter {
    static final HeaderName OCI_REQUEST_ID_HEADER = HeaderNames.create(OciRequestId.OCI_REQUEST_ID);

    @Override
    public void filter(FilterChain filterChain, RoutingRequest routingRequest, RoutingResponse routingResponse) {
        ServerRequestHeaders headers = routingRequest.headers();

        OciRequestId requestId;

        Header requestIdHeader;

        if (headers.contains(OCI_REQUEST_ID_HEADER)) {
            Header receivedHeader = headers.get(OCI_REQUEST_ID_HEADER);

            requestId = OciRequestId.parseUpstreamRequest(receivedHeader.getString());
            requestIdHeader = HeaderValues.create(OCI_REQUEST_ID_HEADER,
                                                  requestId.upstreamHeaderValue());
        } else {
            requestId = OciRequestId.generate();
            requestIdHeader = HeaderValues.create(OCI_REQUEST_ID_HEADER, requestId.upstreamHeaderValue());
        }

        routingRequest.header(requestIdHeader);

        // register requestId in useful contexts
        HelidonMdc.set(OciRequestId.OCI_REQUEST_ID, requestId.upstreamHeaderValue());
        routingRequest.context().register(requestId);

        // must use the upstream header value, as this is the response to our client
        routingResponse.headers()
                .set(requestIdHeader);

        filterChain.proceed();
    }
}
