<?xml version="1.0" encoding="UTF-8"?>
<!--
    Copyright (c) 2023, 2026 Oracle and/or its affiliates.
-->

<project xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance" xmlns="http://maven.apache.org/POM/4.0.0"
        xsi:schemaLocation="http://maven.apache.org/POM/4.0.0 https://maven.apache.org/maven-v4_0_0.xsd">
    <modelVersion>4.0.0</modelVersion>

    <parent>
        <groupId>com.oracle.helidon.oci</groupId>
        <artifactId>helidon-oci-parent</artifactId>
        <version>2.0.0-SNAPSHOT</version>
        <relativePath>../parent/pom.xml</relativePath>
    </parent>

    <artifactId>helidon-oci-bom</artifactId>
    <packaging>pom</packaging>
    <name>Helidon OCI BOM POM</name>

    <properties>
        <helidon.oci.version>2.0.0-SNAPSHOT</helidon.oci.version>
    </properties>

    <dependencyManagement>
        <dependencies>
            <!-- Helidon OCI artifacts -->
            <dependency>
                <groupId>com.oracle.helidon.oci</groupId>
                <artifactId>helidon-oci-codegen</artifactId>
                <version>${helidon.oci.version}</version>
            </dependency>
            <dependency>
                <groupId>com.oracle.helidon.oci.envconfig</groupId>
                <artifactId>helidon-oci-envconfig</artifactId>
                <version>${helidon.oci.version}</version>
            </dependency>
            <dependency>
                <groupId>com.oracle.helidon.oci.errorcode</groupId>
                <artifactId>helidon-oci-errorcode</artifactId>
                <version>${helidon.oci.version}</version>
            </dependency>
            <dependency>
                <groupId>com.oracle.helidon.oci.errorcode</groupId>
                <artifactId>helidon-oci-errorcode-webserver</artifactId>
                <version>${helidon.oci.version}</version>
            </dependency>
            <dependency>
                <groupId>com.oracle.helidon.oci.identity</groupId>
                <artifactId>helidon-oci-identity</artifactId>
                <version>${helidon.oci.version}</version>
            </dependency>
            <dependency>
                <groupId>com.oracle.helidon.oci.metrics</groupId>
                <artifactId>helidon-oci-metrics</artifactId>
                <version>${helidon.oci.version}</version>
            </dependency>
            <dependency>
                <groupId>com.oracle.helidon.oci.metering</groupId>
                <artifactId>helidon-oci-metering-dp</artifactId>
                <version>${helidon.oci.version}</version>
            </dependency>
            <dependency>
                <groupId>com.oracle.helidon.oci.metering</groupId>
                <artifactId>helidon-oci-metering-cp</artifactId>
                <version>${helidon.oci.version}</version>
            </dependency>
            <dependency>
                <groupId>com.oracle.helidon.oci</groupId>
                <artifactId>helidon-oci-audit</artifactId>
                <version>${helidon.oci.version}</version>
            </dependency>
            <dependency>
                <groupId>com.oracle.helidon.oci.requestid</groupId>
                <artifactId>helidon-oci-request-id</artifactId>
                <version>${helidon.oci.version}</version>
            </dependency>
            <dependency>
                <groupId>com.oracle.helidon.oci.requestid</groupId>
                <artifactId>helidon-oci-request-id-webserver</artifactId>
                <version>${helidon.oci.version}</version>
            </dependency>
            <dependency>
                <groupId>com.oracle.helidon.oci.secret-service</groupId>
                <artifactId>helidon-oci-secret-service-config-source</artifactId>
                <version>${helidon.oci.version}</version>
            </dependency>
            <dependency>
                <groupId>com.oracle.helidon.oci.secret-service</groupId>
                <artifactId>helidon-oci-secret-service-tls-manager</artifactId>
                <version>${helidon.oci.version}</version>
            </dependency>
            <dependency>
                <groupId>com.oracle.helidon.oci</groupId>
                <artifactId>helidon-oci-splat</artifactId>
                <version>${helidon.oci.version}</version>
            </dependency>
            <dependency>
                <groupId>com.oracle.helidon.oci</groupId>
                <artifactId>helidon-oci-limits</artifactId>
                <version>${helidon.oci.version}</version>
            </dependency>
            <dependency>
                <groupId>com.oracle.helidon.oci</groupId>
                <artifactId>helidon-oci-tagging</artifactId>
                <version>${helidon.oci.version}</version>
            </dependency>
            <dependency>
                <groupId>com.oracle.helidon.oci</groupId>
                <artifactId>helidon-oci-sdk-common-core</artifactId>
                <version>${helidon.oci.version}</version>
            </dependency>
            <dependency>
                <groupId>com.oracle.helidon.oci.kiev</groupId>
                <artifactId>helidon-oci-kiev</artifactId>
                <version>${helidon.oci.version}</version>
            </dependency>
            <dependency>
                <groupId>com.oracle.helidon.oci.workflow</groupId>
                <artifactId>helidon-oci-workflow</artifactId>
                <version>${helidon.oci.version}</version>
            </dependency>
            <dependency>
                <groupId>com.oracle.helidon.oci</groupId>
                <artifactId>helidon-oci-sdk-common-client</artifactId>
                <version>${helidon.oci.version}</version>
            </dependency>
            <dependency>
                <groupId>com.oracle.helidon.oci</groupId>
                <artifactId>helidon-oci-sdk-oci</artifactId>
                <version>${helidon.oci.version}</version>
            </dependency>
            <dependency>
                <groupId>com.oracle.helidon.oci</groupId>
                <artifactId>helidon-oci-sdk-authentication-instance</artifactId>
                <version>${helidon.oci.version}</version>
            </dependency>
            <dependency>
                <groupId>com.oracle.helidon.oci</groupId>
                <artifactId>helidon-oci-sdk-authentication-resource</artifactId>
                <version>${helidon.oci.version}</version>
            </dependency>
            <dependency>
                <groupId>com.oracle.helidon.oci</groupId>
                <artifactId>helidon-oci-sdk-authentication-oke-workload</artifactId>
                <version>${helidon.oci.version}</version>
            </dependency>
            <dependency>
                <groupId>com.oracle.helidon.oci</groupId>
                <artifactId>helidon-oci-sdk-authentication-service-principal</artifactId>
                <version>${helidon.oci.version}</version>
            </dependency>
            <dependency>
                <groupId>com.oracle.helidon.oci</groupId>
                <artifactId>helidon-oci-identity-client</artifactId>
                <version>${helidon.oci.version}</version>
            </dependency>
            <dependency>
                <groupId>com.oracle.helidon.oci</groupId>
                <artifactId>helidon-oci-sdk-object-storage-client</artifactId>
                <version>${helidon.oci.version}</version>
            </dependency>
            <dependency>
                <groupId>com.oracle.helidon.oci.jaxrs</groupId>
                <artifactId>helidon-oci-jaxrs</artifactId>
                <version>${helidon.oci.version}</version>
            </dependency>
        </dependencies>
    </dependencyManagement>
</project>
