<?xml version="1.0" encoding="UTF-8"?>
<!--
    Copyright (c) 2024, 2026 Oracle and/or its affiliates.
-->

<project xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"
        xmlns="http://maven.apache.org/POM/4.0.0"
        xsi:schemaLocation="http://maven.apache.org/POM/4.0.0 https://maven.apache.org/xsd/maven-4.0.0.xsd">
    <parent>
        <groupId>com.oracle.helidon.oci.tests.integration</groupId>
        <artifactId>helidon-oci-tests-integration</artifactId>
        <version>2.0.0-SNAPSHOT</version>
        <relativePath>../pom.xml</relativePath>
    </parent>
    <modelVersion>4.0.0</modelVersion>

    <artifactId>helidon-oci-tests-integration-dependencies</artifactId>
    <name>Integration Test: OCI Dependencies</name>
    <packaging>pom</packaging>
    <description>These ensure that downstream usages of our ${basedir}/dependencies/pom.xml will work properly</description>

    <properties>
        <!-- Build service property to skip publishing to repo -->
        <skipPublish>true</skipPublish>
    </properties>

    <build>
        <plugins>
            <!-- the enforcer is acting as our test here -->
            <plugin>
                <groupId>org.apache.maven.plugins</groupId>
                <artifactId>maven-enforcer-plugin</artifactId>
            </plugin>

            <plugin>
                <groupId>org.codehaus.mojo</groupId>
                <artifactId>versions-maven-plugin</artifactId>
                <executions>
                    <execution>
                        <phase>install</phase>
                        <goals>
                            <goal>display-property-updates</goal>
                        </goals>
                        <configuration>
                            <includeProperties>
                                oracle-internal-commons-request-id-version,
                                oracle-internal-limits-version,
                                sherlock-version
                            </includeProperties>
                            <!--suppress UnresolvedMavenProperty -->
                            <rulesUri>file://${top.parent.basedir}/build_config/maven-version-rules.xml</rulesUri>
                            <allowIncrementalUpdates>true</allowIncrementalUpdates>
                            <allowMinorUpdates>true</allowMinorUpdates>
                            <allowMajorUpdates>false</allowMajorUpdates>

                            <!-- This files tracks dependency updates that are due -->
                            <!-- Remove the following line if you wish to disable this tracking file feature -->
                            <outputFile>${top.parent.basedir}/bom-dependency-versions.txt</outputFile>

                            <!-- SNAPSHOT versions of the bom should NOT be used in production -->
                            <allowSnapshots>false</allowSnapshots>

                            <!-- Version control already keeps history of the pom file changes -->
                            <generateBackupPoms>false</generateBackupPoms>

                            <includeParent>true</includeParent>
                        </configuration>
                    </execution>
                </executions>
            </plugin>
        </plugins>
    </build>

    <!--
        These dependencies were produced by calling
        > cat ../../../dependencies/pom.xml | ../../../etc/scripts/depm2dep.sh
        see README.md for details.
    -->
    <dependencies/>

</project>
