<?xml version="1.0" encoding="UTF-8"?>
<!--
    Copyright (c) 2024, 2025 Oracle and/or its affiliates.
-->

<project xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"
        xmlns="http://maven.apache.org/POM/4.0.0"
        xsi:schemaLocation="http://maven.apache.org/POM/4.0.0 https://maven.apache.org/xsd/maven-4.0.0.xsd">
    <parent>
        <groupId>com.oracle.helidon.oci.tests.integration</groupId>
        <artifactId>helidon-oci-tests-integration</artifactId>
        <version>2.0.0-SNAPSHOT</version>
        <relativePath>../pom.xml</relativePath>
    </parent>
    <modelVersion>4.0.0</modelVersion>

    <artifactId>helidon-oci-tests-integration-swagger-maven-plugin</artifactId>
    <name>Integration Test: Helidon OCI Swagger Maven Plugin</name>
    <description>Verifies code produced by the code generator compiles</description>

    <properties>
        <project.build.sourceEncoding>UTF-8</project.build.sourceEncoding>
        <version.plugin.jandex>3.1.2</version.plugin.jandex>
        <version.lib.jackson.databind.nullable>0.2.3</version.lib.jackson.databind.nullable>
        <!-- Build service property to skip publishing to repo -->
        <skipPublish>true</skipPublish>
    </properties>

    <dependencies>
        <dependency>
            <groupId>io.helidon.microprofile.bundles</groupId>
            <artifactId>helidon-microprofile-core</artifactId>
        </dependency>
        <dependency>
            <groupId>io.helidon.microprofile.cdi</groupId>
            <artifactId>helidon-microprofile-cdi</artifactId>
        </dependency>
        <dependency>
            <groupId>jakarta.enterprise</groupId>
            <artifactId>jakarta.enterprise.cdi-api</artifactId>
        </dependency>
        <dependency>
            <groupId>jakarta.ws.rs</groupId>
            <artifactId>jakarta.ws.rs-api</artifactId>
        </dependency>
        <dependency>
            <groupId>com.fasterxml.jackson.core</groupId>
            <artifactId>jackson-annotations</artifactId>
        </dependency>
        <dependency>
            <groupId>com.fasterxml.jackson.core</groupId>
            <artifactId>jackson-databind</artifactId>
        </dependency>
        <dependency>
            <groupId>org.openapitools</groupId>
            <artifactId>jackson-databind-nullable</artifactId>
            <version>${version.lib.jackson.databind.nullable}</version>
        </dependency>
        <dependency>
            <groupId>org.glassfish.jersey.media</groupId>
            <artifactId>jersey-media-json-jackson</artifactId>
        </dependency>
        <dependency>
            <groupId>com.fasterxml.jackson.datatype</groupId>
            <artifactId>jackson-datatype-jsr310</artifactId>
        </dependency>
        <dependency>
            <groupId>io.helidon.microprofile.bean-validation</groupId>
            <artifactId>helidon-microprofile-bean-validation</artifactId>
        </dependency>
        <dependency>
            <groupId>org.jboss</groupId>
            <artifactId>jandex</artifactId>
            <scope>runtime</scope>
            <version>${version.plugin.jandex}</version>
        </dependency>
        <dependency>
            <groupId>org.junit.jupiter</groupId>
            <artifactId>junit-jupiter-api</artifactId>
            <scope>test</scope>
        </dependency>
        <dependency>
            <groupId>org.hamcrest</groupId>
            <artifactId>hamcrest-all</artifactId>
            <scope>test</scope>
        </dependency>
        <dependency>
            <groupId>io.helidon.microprofile.testing</groupId>
            <artifactId>helidon-microprofile-testing-junit5</artifactId>
            <scope>test</scope>
        </dependency>
    </dependencies>

    <build>
        <plugins>
            <plugin>
                <groupId>org.apache.maven.plugins</groupId>
                <artifactId>maven-dependency-plugin</artifactId>
                <executions>
                    <execution>
                        <id>copy-libs</id>
                    </execution>
                </executions>
            </plugin>
            <plugin>
                <groupId>io.smallrye</groupId>
                <artifactId>jandex-maven-plugin</artifactId>
                <version>${version.plugin.jandex}</version>
                <executions>
                    <execution>
                        <id>make-index</id>
                        <goals>
                            <goal>jandex</goal>
                        </goals>
                        <phase>process-classes</phase>
                    </execution>
                </executions>
            </plugin>
            <plugin>
                <groupId>com.oracle.helidon.oci</groupId>
                <artifactId>helidon-oci-swagger-maven-plugin</artifactId>
                <version>${project.version}</version>
                <executions>
                    <execution>
                        <goals>
                            <goal>generate</goal>
                        </goals>
                        <configuration>
                            <basePackage>com.oracle.tests.integration</basePackage>
                            <language>oracle-java-helidon-service</language>
                            <specPath>${project.basedir}/reference-spec.yaml</specPath>
                            <additionalProperties>
                                <!-- Telling SDK and generator to use Jakarta namespace or not -->
                                <useJakartaAnnotations>true</useJakartaAnnotations>
                                <!-- This is shared between SDK model and our service gen -->
                                <enableValidation>true</enableValidation>
                                <!-- Same as default set in code but still setting here as reference -->
                                <contextsJaxRsHttpHeaders>false</contextsJaxRsHttpHeaders>
                                <contextsJaxRsUriInfo>false</contextsJaxRsUriInfo>
                                <contextsJaxRsRequest>false</contextsJaxRsRequest>
                                <contextsJaxRsSecurityContext>false</contextsJaxRsSecurityContext>
                                <contextsAuthProxyIdentity>false</contextsAuthProxyIdentity>
                                <contextsAuditPayloadAppender>false</contextsAuditPayloadAppender>
                                <contextsContainerRequest>false</contextsContainerRequest>
                                <contextsContainerRequest>false</contextsContainerRequest>
                                <useJaxRsServiceResponse>false</useJaxRsServiceResponse>
                            </additionalProperties>
                            <project/>
                        </configuration>
                    </execution>
                </executions>
            </plugin>
        </plugins>
    </build>
</project>
